QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`]          = { ["name"] = "weapon_unarmed",        ["label"] = "Fists",                ["damagereason"] = "Whacked", },
	[`weapon_dagger`]           = { ["name"] = "weapon_dagger",         ["label"] = "Dagger",               ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_bat`]              = { ["name"] = "weapon_bat",            ["label"] = "Bat",                  ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_bottle`]           = { ["name"] = "weapon_bottle",         ["label"] = "Broken Bottle",        ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Stabbed", },
	[`weapon_crowbar`]          = { ["name"] = "weapon_crowbar",        ["label"] = "Crowbar",              ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_flashlight`]       = { ["name"] = "weapon_flashlight",     ["label"] = "Flashlight",           ["damagereason"] = "Whacked", },
	[`weapon_golfclub`] 		= { ["name"] = "weapon_golfclub", 		["label"] = "Golfclub",             ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_hammer`]           = { ["name"] = "weapon_hammer",         ["label"] = "Hammer",               ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_hatchet`]          = { ["name"] = "weapon_hatchet",        ["label"] = "Hatchet",              ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_knuckle`]          = { ["name"] = "weapon_knuckle",        ["label"] = "Knuckle",              ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_knife`]            = { ["name"] = "weapon_knife",          ["label"] = "Knife",                ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_machete`]          = { ["name"] = "weapon_machete",        ["label"] = "Machete",              ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_switchblade`]      = { ["name"] = "weapon_switchblade",    ["label"] = "Switchblade",          ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Stabbed", },
	[`weapon_nightstick`]       = { ["name"] = "weapon_nightstick",     ["label"] = "Nightstick",           ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_wrench`] 			= { ["name"] = "weapon_wrench", 		["label"] = "Wrench",              	["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_battleaxe`]        = { ["name"] = "weapon_battleaxe",      ["label"] = "Battle Axe",           ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_poolcue`]          = { ["name"] = "weapon_poolcue",        ["label"] = "Poolcue",              ["durability"] = 0.15, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_briefcase`]        = { ["name"] = "weapon_briefcase",      ["label"] = "Briefcase",            ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Whacked", },
	[`weapon_briefcase_02`]     = { ["name"] = "weapon_briefcase_02",   ["label"] = "Briefcase",            ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Whacked", },
	[`weapon_garbagebag`]       = { ["name"] = "weapon_garbagebag",     ["label"] = "Garbage Bag",          ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Whacked", },
	[`weapon_handcuffs`]        = { ["name"] = "weapon_handcuffs",      ["label"] = "Handcuffs",            ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Whacked", },
	[`weapon_bread`]            = { ["name"] = "weapon_bread",          ["label"] = "Baquette",             ["durability"] = 0.15, ["class"] = "A", ["damagereason"] = "Whacked", },
	[`weapon_stone_hatchet`]    = { ["name"] = "weapon_stone_hatchet",  ["label"] = "Weapon Stone Hatchet", ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },
	[`weapon_candycane`]        = { ["name"] = "weapon_candycane",      ["label"] = "Candy Cane",           ["durability"] = 0.15, ["class"] = "B", ["damagereason"] = "Stabbed", },

	-- Handguns
	[`weapon_pistol`] = {
		["name"] = "weapon_pistol",
		["label"] = "Walther P99",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_PISTOL_CLIP_01", item = "pistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_PISTOL_CLIP_02", item = "pistol_extendedclip", type = "clip", },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight", },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP_02", item = "pistol_suppressor", },
			["luxuryfinish"] = { component = "COMPONENT_PISTOL_VARMOD_LUXE", item = "pistol_luxuryfinish", },
		},
	},
	[`weapon_combatpistol`] = {
		["name"] = "weapon_combatpistol",
		["label"] = "Combat Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_COMBATPISTOL_CLIP_01", item = "combatpistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_COMBATPISTOL_CLIP_02", item = "combatpistol_extendedclip", type = "clip", },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight", },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "pistol_suppressor", },
			["luxuryfinish"] = { component = "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER", item = "combatpistol_luxuryfinish", },
		},
	},
	[`weapon_appistol`] = {
		["name"] = "weapon_appistol",
		["label"] = "AP Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_APPISTOL_CLIP_01", item = "appistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_APPISTOL_CLIP_02", item = "appistol_extendedclip", type = "clip", },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight", },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "pistol_suppressor", },
			["luxuryfinish"] = { component = "COMPONENT_APPISTOL_VARMOD_LUXE", item = "appistol_luxuryfinish", },
		},
	},
	[`weapon_pistol50`] = {
		["name"] = "weapon_pistol50",
		["label"] = "Pistol .50 Cal",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.6,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_PISTOL50_CLIP_01", item = "pistol50_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_PISTOL50_CLIP_02", item = "pistol50_extendedclip", type = "clip", },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight", },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "pistol_suppressor", },
			["luxuryfinish"] = { component = "COMPONENT_PISTOL50_VARMOD_LUXE", item = "pistol50_luxuryfinish", },
		},
	},
	[`weapon_pistol_mk2`] = {
		["name"] = "weapon_pistol_mk2",
		["label"] = "Pistol Mk II",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_PISTOL_MK2_CLIP_01", item = "pistol_mk2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_PISTOL_MK2_CLIP_02", item = "pistol_mk2_extendedclip", type = "clip" },
			["tracerrounds"] = { component = "COMPONENT_PISTOL_MK2_CLIP_TRACER", item = "pistol_mk2_tracerrounds", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", item = "pistol_mk2_icendrounds" },
			["hollowrounds"] = { component = "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", item = "pistol_mk2_hollowrounds", type = "clip" },
			["fmjrounds"] = { component = "COMPONENT_PISTOL_MK2_CLIP_FMJ", item = "pistol_mk2_fmjrounds" },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH_02", item = "pistol_flashlight" },
			["scope"] = { component = "COMPONENT_AT_PI_RAIL", item = "pistol_scope" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP_02", item = "pistol_suppressor", type = "silencer" },
			["compensator"] = { component = "COMPONENT_AT_PI_COMP", item = "pistol_mk2_compensator" },
		},

	},
	[`weapon_stungun`] = {
		["name"] = "weapon_stungun",
		["label"] = "Taser",
		["ammotype"] = "AMMO_STUNGUN",
		["damagereason"] = "Tased",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_snspistol`] = {
		["name"] = "weapon_snspistol",
		["label"] = "SNS Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SNSPISTOL_CLIP_01", item = "snspistol_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_SNSPISTOL_CLIP_02", item = "snspistol_extendedclip", type = "clip" },
			["grip"] = { component = "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER", item = "snspistol_grip" },
		},
	},
	[`weapon_snspistol_mk2`] = {
		["name"] = "weapon_snspistol_mk2",
		["label"] = "SNS Pistol MK2",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_heavypistol`] = {
		["name"] = "weapon_heavypistol",
		["label"] = "Heavy Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_HEAVYPISTOL_CLIP_01", item = "heavypistol_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_HEAVYPISTOL_CLIP_02", item = "heavypistol_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "pistol_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_HEAVYPISTOL_VARMOD_LUXE", item = "heavypistol_grip" },
		},
	},
	[`weapon_vintagepistol`] = {
		["name"] = "weapon_vintagepistol",
		["label"] = "Vintage Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_VINTAGEPISTOL_CLIP_01", item = "vintagepistol_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_VINTAGEPISTOL_CLIP_02", item = "vintagepistol_extendedclip", type = "clip" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "pistol_suppressor", type = "silencer" },
		},
	},
	[`weapon_flaregun`] = {
		["name"] = "weapon_flaregun",
		["label"] = "Flare Gun",
		["ammotype"] = "AMMO_FLARE",
		["damagereason"] = "Burned",
		["recoil"] = 0.9,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_marksmanpistol`] = {
		["name"] = "weapon_marksmanpistol",
		["label"] = "Marksman Pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.9,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_revolver`] = {
		["name"] = "weapon_revolver",
		["label"] = "Revolver",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.6,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_REVOLVER_CLIP_01", item = "revolver_defaultclip" },
			["vipvariant"] = { component = "COMPONENT_REVOLVER_VARMOD_GOON", item = "revolver_vipvariant", type = "skin" },
			["bodyguardvariant"] = { component = "COMPONENT_REVOLVER_VARMOD_BOSS", item = "revolver_bodyguardvariant", type = "skin" },
		},
	},
	[`weapon_revolver_mk2`] = {
		["name"] = "weapon_revolver_mk2",
		["label"] = "Violence",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.6,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_doubleaction`] = {
		["name"] = "weapon_doubleaction",
		["label"] = "Double Action Revolver",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_raypistol`] = {
		["name"] = "weapon_raypistol",
		["label"] = "Weapon Raypistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 6,
		["attachments"] = {},
	},
	[`weapon_ceramicpistol`] = {
		["name"] = "weapon_ceramicpistol",
		["label"] = "Weapon Ceramicpistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_CERAMICPISTOL_CLIP_01", item = "ceramicpistol_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_CERAMICPISTOL_CLIP_02", item = "ceramicpistol_extendedclip", type = "clip" },
			["suppressor"] = { component = "COMPONENT_CERAMICPISTOL_SUPP", item = "pistol_suppressor", type = "silencer" },
		},
	},
	[`weapon_navyrevolver`] = {
		["name"] = "weapon_navyrevolver",
		["label"] = "Weapon Navyrevolver",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_gadgetpistol`] = {
		["name"] = "weapon_gadgetpistol",
		["label"] = "Weapon Gadgetpistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_stungun_mp`] 			 = {["name"] = "weapon_stungun_mp", 	["label"] = "Taser", 					["ammotype"] = "AMMO_STUNGUN",	["damagereason"] = "Died"},
	[`weapon_pistolxm3`] 			 = {["name"] = "weapon_pistolxm3", 	["label"] = "Pistol XM3", 					["ammotype"] = "AMMO_PISTOL",	["damagereason"] = "Died"},

    -- Submachine Guns
	[`weapon_microsmg`] = {
		["name"] = "weapon_microsmg",
		["label"] = "Micro SMG",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MICROSMG_CLIP_01", item = "microsmg_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MICROSMG_CLIP_02", item = "microsmg_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "smg_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "smg_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "smg_suppressor", type = "silencer" },
			["luxuryfinish"] = { component = "COMPONENT_MICROSMG_VARMOD_LUXE", item = "microsmg_luxuryfinish" },
		},
	},
	[`weapon_smg`] = {
		["name"] = "weapon_smg",
		["label"] = "SMG",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SMG_CLIP_01", item = "smg_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_SMG_CLIP_02", item = "smg_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_SMG_CLIP_03", item = "smg_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "smg_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO_02", item = "smg_scope" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "smg_suppressor", type = "silencer" },
			["luxuryfinish"] = { component = "COMPONENT_SMG_VARMOD_LUXE", item = "smg_luxuryfinish" },
		},
	},
	[`weapon_smg_mk2`] = {
		["name"] = "weapon_smg_mk2",
		["label"] = "PD MP5 2",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SMG_MK2_CLIP_01", item = "smg_mk2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_SMG_MK2_CLIP_02", item = "smg_mk2_extendedclip", type = "clip" },
			["tracerrounds"] = { component = "COMPONENT_SMG_MK2_CLIP_TRACER", item = "smg_mk2_tracerrounds", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_SMG_MK2_CLIP_INCENDIARY", item = "smg_mk2_icendrounds", type = "clip" },
			["hollowrounds"] = { component = "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", item = "smg_mk2_hollowrounds", type = "clip" },
			["fmjrounds"] = { component = "COMPONENT_SMG_MK2_CLIP_FMJ", item = "smg_mk2_fmjrounds", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "smg_flashlight" },
			["heavybarrel"] = { component = "COMPONENT_AT_SB_BARREL_02", item = "smg_mk2_heavybarrel" },
			["scope"] = { component = "COMPONENT_AT_SIGHTS_SMG", item = "smg_scope" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "smg_suppressor", type = "silencer" },
		},
	},
	[`weapon_assaultsmg`] = {
		["name"] = "weapon_assaultsmg",
		["label"] = "Assault SMG",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_ASSAULTSMG_CLIP_01", item = "assaultsmg_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_ASSAULTSMG_CLIP_02", item = "assaultsmg_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "smg_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "smg_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "smg_suppressor", type = "silencer" },
			["luxuryfinish"] = { component = "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER", item = "assaultsmg_luxuryfinish" },
		},
	},
	[`weapon_combatpdw`] = {
		["name"] = "weapon_combatpdw",
		["label"] = "Combat PDW",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_COMBATPDW_CLIP_01", item = "combatpdw_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_COMBATPDW_CLIP_02", item = "combatpdw_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_COMBATPDW_CLIP_03", item = "combatpdw_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "smg_flashlight" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "combatpdw_grip" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_SMALL", item = "smg_scope" },
		},
	},
	[`weapon_machinepistol`] = {
		["name"] = "weapon_machinepistol",
		["label"] = "Tec-9",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MACHINEPISTOL_CLIP_01", item = "machinepistol_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MACHINEPISTOL_CLIP_02", item = "machinepistol_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_MACHINEPISTOL_CLIP_03", item = "machinepistol_drum", type = "clip" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "pistol_suppressor", type = "silencer" },
		},
	},
	[`weapon_minismg`] = {
		["name"] = "weapon_minismg",
		["label"] = "Mini SMG",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MINISMG_CLIP_01", item = "minismg_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MINISMG_CLIP_02", item = "minismg_extendedclip", type = "clip" },
		},
	},
	[`weapon_raycarbine`] = {
		["name"] = "weapon_raycarbine",
		["label"] = "Weapon Raycarbine",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 6,
		["attachments"] = {},
	},

    -- Shotguns
	[`weapon_pumpshotgun`] = {
		["name"] = "weapon_pumpshotgun",
		["label"] = "Pump Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_SR_SUPP", item = "shotgun_suppressor", type = "silencer" },
			["luxuryfinish"] = { component = "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER", item = "pumpshotgun_luxuryfinish" },
		},
	},
	[`weapon_pumpshotgun_mk2`] = {
		["name"] = "weapon_pumpshotgun_mk2",
		["label"] = "Pumpshotgun MK2",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", item = "pumpshotgun_mk2_defaultshells", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", item = "pumpshotgun_mk2_icendrounds", type = "clip" },
			["explorounds"] = { component = "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", item = "pumpshotgun_mk2_explorounds", type = "clip" },
			["scope"] = { component = "COMPONENT_AT_SIGHTS", item = "shotgun_scope" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_SR_SUPP_03", item = "shotgun_suppressor", type = "silencer" },
		},
	},
	[`weapon_sawnoffshotgun`] = {
		["name"] = "weapon_sawnoffshotgun",
		["label"] = "Sawn-off Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.7,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["luxuryfinish"] = { component = "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE", item = "sawnoffshotgun_luxuryfinish", },
		},
	},
	[`weapon_assaultshotgun`] = {
		["name"] = "weapon_assaultshotgun",
		["label"] = "Assault Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_ASSAULTSHOTGUN_CLIP_01", item = "assaultshotgun_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_ASSAULTSHOTGUN_CLIP_02", item = "assaultshotgun_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "shotgun_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "shotgun_grip" },
		},
	},
	[`weapon_bullpupshotgun`] = {
		["name"] = "weapon_bullpupshotgun",
		["label"] = "Bullpup Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "shotgun_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "shotgun_grip" },
		},
	},
	[`weapon_musket`] = {
		["name"] = "weapon_musket",
		["label"] = "Musket",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.7,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_heavyshotgun`] = {
		["name"] = "weapon_heavyshotgun",
		["label"] = "Heavy Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_HEAVYSHOTGUN_CLIP_01", item = "heavyshotgun_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_HEAVYSHOTGUN_CLIP_02", item = "heavyshotgun_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_HEAVYSHOTGUN_CLIP_03", item = "heavyshotgun_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "shotgun_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "shotgun_grip" },
		},
	},
	[`weapon_dbshotgun`] = {
		["name"] = "weapon_dbshotgun",
		["label"] = "Double-barrel Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.7,
		["durability"] = 0.15,
		["class"] = 2,
		["attachments"] = {
			["extendedclip"] = { component = "COMPONENT_HEAVYSHOTGUN_CLIP_02", item = "dbshotgun_extendedclip", type = "clip" },
		},
	},
	[`weapon_autoshotgun`] = {
		["name"] = "weapon_autoshotgun",
		["label"] = "Auto Shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {},
	},
	[`weapon_combatshotgun`] = {
		["name"] = "weapon_combatshotgun",
		["label"] = "Weapon Combatshotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Pulverized",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "shotgun_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "shotgun_suppressor", type = "silencer" },
		},
	},
    -- Assault Rifles
	[`weapon_assaultrifle`] = {
		["name"] = "weapon_assaultrifle",
		["label"] = "Assault Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_01", item = "assaultrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_02", item = "assaultrifle_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_03", item = "assaultrifle_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE", item = "assaultrifle_luxuryfinish" },
		},
	},
	[`weapon_assaultrifle_mk2`] = {
		["name"] = "weapon_assaultrifle_mk2",
		["label"] = "AK-47 MK2",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", item = "assaultrifle_mk2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", item = "assaultrifle_mk2_extendedclip", type = "clip" },
			["tracerrounds"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", item = "assaultrifle_mk2_tracerrounds", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", item = "assaultrifle_mk2_icendrounds", type = "clip" },
			["armorrounds"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", item = "assaultrifle_mk2_armorrounds", type = "clip" },
			["fmjrounds"] = { component = "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", item = "assaultrifle_mk2_fmjrounds", type = "clip" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP_02", item = "rifle_grip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SIGHTS", item = "rifle_scope" },
			-- ["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MEDIUM_MK2", item = "assaultrifle_mk2_largescope", type = "scope" },
			["heavybarrel"] = { component = "COMPONENT_AT_AR_BARREL_02", item = "assaultrifle_mk2_heavybarrel" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "silencer" },
		},
	},
	[`weapon_carbinerifle`] = {
		["name"] = "weapon_carbinerifle",
		["label"] = "Carbine Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_CARBINERIFLE_CLIP_01", item = "carbinerifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_CARBINERIFLE_CLIP_02", item = "carbinerifle_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_CARBINERIFLE_CLIP_03", item = "carbinerifle_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MEDIUM", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_CARBINERIFLE_VARMOD_LUXE", item = "carbinerifle_luxuryfinish" },
		},
	},
    [`weapon_carbinerifle_mk2`] = {
		["name"] = "weapon_carbinerifle_mk2",
		["label"] = "PD 762",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {},
	},
	[`weapon_advancedrifle`] = {
		["name"] = "weapon_advancedrifle",
		["label"] = "Advanced Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_ADVANCEDRIFLE_CLIP_01", item = "advancedrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_ADVANCEDRIFLE_CLIP_02", item = "advancedrifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_SMALL", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE", item = "advancedrifle_luxuryfinish" },
		},
	},
	[`weapon_specialcarbine`] = {
		["name"] = "weapon_specialcarbine",
		["label"] = "Special Carbine",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SPECIALCARBINE_CLIP_01", item = "specialcarbine_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_SPECIALCARBINE_CLIP_02", item = "specialcarbine_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_SPECIALCARBINE_CLIP_03", item = "specialcarbine_drum", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MEDIUM", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER", item = "specialcarbine_luxuryfinish" },
		},
	},
	[`weapon_specialcarbine_mk2`] = {
		["name"] = "weapon_specialcarbine_mk2",
		["label"] = "Weapon Wpecialcarbine MK2",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_01", item = "specialcarbine_mk2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", item = "specialcarbine_mk2_extendedclip", type = "clip" },
			["tracerrounds"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", item = "specialcarbine_mk2_tracerrounds", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", item = "specialcarbine_mk2_icendrounds", type = "clip" },
			["armorrounds"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", item = "specialcarbine_mk2_armorrounds", type = "clip" },
			["fmjrounds"] = { component = "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", item = "specialcarbine_mk2_fmjrounds", type = "clip" },
			-- ["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MEDIUM_MK2", item = "specialcarbine_mk2_largescope", type = "scope" },
			["heavybarrel"] = { component = "COMPONENT_AT_SC_BARREL_02", item = "specialcarbine_mk2_heavybarrel" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SIGHTS", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP_02", item = "rifle_grip" },
		},
	},
	--[[[`weapon_bullpuprifle`] = {
		["name"] = "weapon_bullpuprifle",
		["label"] = "Bullpup Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_BULLPUPRIFLE_CLIP_01", item = "bullpuprifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_BULLPUPRIFLE_CLIP_02", item = "bullpuprifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_SMALL", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_BULLPUPRIFLE_VARMOD_LOW", item = "bullpuprifle_luxuryfinish" },
		},
	},]]
	[`weapon_bullpuprifle_mk2`] = {
		["name"] = "weapon_bullpuprifle_mk2",
		["label"] = "Bull Puprifle MK2",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", item = "bullpuprifle_mk2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", item = "bullpuprifle_mk2_extendedclip", type = "clip" },
			["tracerrounds"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", item = "bullpuprifle_mk2_tracerrounds", type = "clip" },
			["icendrounds"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", item = "bullpuprifle_mk2_icendrounds", type = "clip" },
			["armorrounds"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", item = "bullpuprifle_mk2_armorrounds", type = "clip" },
			["fmjrounds"] = { component = "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", item = "bullpuprifle_mk2_fmjrounds", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SIGHTS", item = "rifle_scope" },
			-- ["advancedscope"] = { component = "COMPONENT_AT_SCOPE_SMALL_MK2", item = "bullpuprifle_mk2_mediumscope", type = "scope" },
			["heavybarrel"] = { component = "COMPONENT_AT_BP_BARREL_02", item = "bullpuprifle_mk2_heavybarrel" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP_02", item = "rifle_grip" },
		},
	},
	[`weapon_compactrifle`] = {
		["name"] = "weapon_compactrifle",
		["label"] = "Compact Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_COMPACTRIFLE_CLIP_01", item = "compactrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_COMPACTRIFLE_CLIP_02", item = "compactrifle_extendedclip", type = "clip" },
			["drum"] = { component = "COMPONENT_COMPACTRIFLE_CLIP_03", item = "compactrifle_drum", type = "clip" },
		},
	},
	[`weapon_militaryrifle`] = {
		["name"] = "weapon_militaryrifle",
		["label"] = "Weapon Militaryrifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MILITARYRIFLE_CLIP_01", item = "militaryrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MILITARYRIFLE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_SMALL", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["sight"] = { component = "COMPONENT_MILITARYRIFLE_SIGHT_01", item = "rifle_scope" },
		},
	},
    [`weapon_heavyrifle`] = {
		["name"] = "weapon_heavyrifle",
		["label"] = "Heavy Rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 3,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_HEAVYRIFLE_CLIP_01", item = "militaryrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_HEAVYRIFLE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MEDIUM", item = "rifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
			["luxuryfinish"] = { component = "COMPONENT_BULLPUPRIFLE_VARMOD_LOW", item = "bullpuprifle_luxuryfinish" },
		},
	},
    [`weapon_tacticalrifle`] = {
        ["name"] = "weapon_tacticalrifle",
        ["label"] = "Tactical Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["damagereason"] = "Floored",
        ["recoil"] = 0.4,
		["durability"] = 0.15,
		["class"] = 3,
        ["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_TACTICALRIFLE_CLIP_01", item = "tacticalrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_TACTICALRIFLE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH_REH", item = "rifle_flashlight" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip" },
		},
    },

    -- Light Machine Guns
	[`weapon_mg`] = {
		["name"] = "weapon_mg",
		["label"] = "Machinegun",
		["ammotype"] = "AMMO_MG",
		["damagereason"] = "Sprayed",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_combatmg`] = {
		["name"] = "weapon_combatmg",
		["label"] = "Combat MG",
		["ammotype"] = "AMMO_MG",
		["damagereason"] = "Sprayed",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_combatmg_mk2`] = {
		["name"] = "weapon_combatmg_mk2",
		["label"] = "Weapon Combatmg MK2",
		["ammotype"] = "AMMO_MG",
		["damagereason"] = "Sprayed",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_gusenberg`] = {
		["name"] = "weapon_gusenberg",
		["label"] = "Thompson SMG",
		["ammotype"] = "AMMO_MG",
		["damagereason"] = "Sprayed",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_GUSENBERG_CLIP_01", item = "gusenberg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_GUSENBERG_CLIP_02", item = "gusenberg_extendedclip", type = "clip", },
		},
	},

    -- Sniper Rifles
	[`weapon_sniperrifle`] = {
		["name"] = "weapon_sniperrifle",
		["label"] = "Sniper Rifle",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SNIPERRIFLE_CLIP_01", item = "sniperrifle_defaultclip" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "sniper_suppressor", type = "silencer" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE", item = "sniper_scope", type = "scope" },
			["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MAX", item = "snipermax_scope", type = "scope" },
			["grip"] = { component = "COMPONENT_SNIPERRIFLE_VARMOD_LUXE", item = "sniper_grip" },
		},
	},
	[`weapon_sniperrifle2`] = {
		["name"] = "weapon_sniperrifle2",
		["label"] = "Hunting Rifle",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_SNIPERRIFLE_CLIP_01", item = "sniperrifle_defaultclip", },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "sniper_suppressor", },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE", item = "sniper_scope", type = "scope", },
			["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MAX", item = "snipermax_scope", type = "scope", },
			["grip"] = { component = "COMPONENT_SNIPERRIFLE_VARMOD_LUXE", item = "sniper_grip", },
		},
	},
	[`weapon_heavysniper`] = {
		["name"] = "weapon_heavysniper",
		["label"] = "Heavy Sniper",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.6,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_HEAVYSNIPER_CLIP_01", item = "heavysniper_defaultclip", },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE", item = "sniper_scope", type = "scope", },
			["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MAX", item = "snipermax_scope", type = "scope", },
		},
	},
	[`weapon_heavysniper_mk2`] = {
		["name"] = "weapon_heavysniper_mk2",
		["label"] = "Weapon Heavysniper MK2",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.6,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_HEAVYSNIPER_CLIP_01", item = "heavysniper_defaultclip" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE", item = "sniper_scope", type = "scope" },
			["advancedscope"] = { component = "COMPONENT_AT_SCOPE_MAX", item = "snipermax_scope", type = "scope" },
		},
	},
	[`weapon_marksmanrifle`] = {
		["name"] = "weapon_marksmanrifle",
		["label"] = "Marksman Rifle",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MARKSMANRIFLE_CLIP_01", item = "marksmanrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MARKSMANRIFLE_CLIP_02", item = "marksmanrifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "sniper_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", item = "marksmanrifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "sniper_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "sniper_grip" },
			["luxuryfinish"] = { component = "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE", item = "marksmanrifle_luxuryfinish" },
		},
	},
	[`weapon_marksmanrifle_mk2`] = {
		["name"] = "weapon_marksmanrifle_mk2",
		["label"] = "Weapon Marksmanrifle MK2",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 3,
		["durability"] = 0.15,
		["class"] = 4,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_MARKSMANRIFLE_CLIP_01", item = "marksmanrifle_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_MARKSMANRIFLE_CLIP_02", item = "marksmanrifle_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "sniper_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", item = "marksmanrifle_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "sniper_suppressor", type = "silencer" },
			["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "sniper_grip" },
			["luxuryfinish"] = { component = "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE", item = "marksmanrifle_luxuryfinish" },
		},
	},
	[`weapon_remotesniper`] = {
		["name"] = "weapon_remotesniper",
		["label"] = "Remote Sniper",
		["ammotype"] = "AMMO_SNIPER_REMOTE",
		["recoil"] = 1.2,
		["class"] = 4,
		["damagereason"] = "Sniped"
	},
    [`weapon_precisionrifle`] = {
        ["name"] = "weapon_precisionrifle",
        ["label"] = "Precision Rifle",
        ["ammotype"] = "AMMO_SNIPER",
        ["recoil"] = 0.3,
        ["durability"] = 0.15,
		["class"] = 4,
        ["damagereason"] = "Sniped",
        ["attachments"] = {},
    },

    -- Heavy Weapons
	[`weapon_firework`] = {
		["name"] = "weapon_firework",
		["label"] = "Firework Launcher",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Obliterated",
	},
	[`weapon_railgun`] = {
		["name"] = "weapon_railgun",
		["label"] = "Railgun",
		["recoil"] = 2.4,
		["durability"] = 0.15,
		["class"] = 6,
		["damagereason"] = "Obliterated",
	},
	[`weapon_compactlauncher`] = {
		["name"] = "weapon_compactlauncher",
		["label"] = "Compact Launcher",
		["recoil"] = 0.5,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Obliterated",
	},
	[`weapon_rpg`] = {
		["name"] = "weapon_rpg",
		["label"] = "RPG",
		["recoil"] = 0.0,
		["durability"] = 0.15,
		["class"] = 5,
		["ammotype"] = "AMMO_RPG",
		["damagereason"] = "Obliterated",
	},
	[`weapon_grenadelauncher`] = {
		["name"] = "weapon_grenadelauncher",
		["label"] = "Grenade Launcher",
		["recoil"] = 1.0,
		["durability"] = 0.15,
		["class"] = 5,
		["ammotype"] = "AMMO_GRENADELAUNCHER",
		["damagereason"] = "Obliterated",
	},
	[`weapon_grenadelauncher_smoke`] = {
		["name"] = "weapon_grenadelauncher_smoke",
		["label"] = "Smoke Grenade Launcher",
		["recoil"] = 1.0,
		["durability"] = 0.15,
		["class"] = 5,
		["ammotype"] = "AMMO_GRENADELAUNCHER",
		["damagereason"] = "Obliterated",
	},
	[`weapon_minigun`] = {
		["name"] = "weapon_minigun",
		["label"] = "Minigun",
		["recoil"] = 0.1,
		["durability"] = 0.15,
		["ammotype"] = "AMMO_MINIGUN",
		["class"] = 4,
		["damagereason"] = "Obliterated",
	},
	[`weapon_hominglauncher`] = {
		["name"] = "weapon_hominglauncher",
		["label"] = "Homing Launcher",
		["recoil"] = 0.0,
		["durability"] = 0.15,
		["class"] = 5,
		["ammotype"] = "AMMO_STINGER",
		["damagereason"] = "Obliterated",
	},
	[`weapon_rayminigun`] = {
		["name"] = "weapon_rayminigun",
		["label"] = "Weapon Rayminigun",
		["recoil"] = 0.3,
		["durability"] = 0.15,
		["ammotype"] = "AMMO_MINIGUN",
		["class"] = 6,
		["damagereason"] = "Obliterated",
	},
    [`weapon_emplauncher`] 			 = {
		["name"] = "weapon_emplauncher",
		["label"] = "EMP Launcher",
		["ammotype"] = "AMMO_EMPLAUNCHER",
		["damagereason"] = "Died",
		["durability"] = 0.15,
		["class"] = 5,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_EMPLAUNCHER_CLIP_01", item = "emplauncher_defaultclip", type = "clip", },
		},
	},

    -- Throwables
	[`weapon_grenade`] = {
		["name"] = "weapon_grenade",
		["label"] = "Grenade",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Exploded",
	},
	[`weapon_bzgas`] = {
		["name"] = "weapon_bzgas",
		["label"] = "BZ Gas",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Died",
	},
	[`weapon_molotov`] = {
		["name"] = "weapon_molotov",
		["label"] = "Molotov",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Torched",
	},
	[`weapon_stickybomb`] = {
		["name"] = "weapon_stickybomb",
		["label"] = "C4",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Exploded",
	},
	[`weapon_proxmine`] = {
		["name"] = "weapon_proxmine",
		["label"] = "Proxmine Grenade",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Exploded",
	},
	[`weapon_snowball`] = {
		["name"] = "weapon_snowball",
		["label"] = "Snowball",
		["throwable"] = true,
		["durability"] = 0.15,
		["damagereason"] = "Died",
	},
	[`weapon_pipebomb`] = {
		["name"] = "weapon_pipebomb",
		["label"] = "Pipe Bomb",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Exploded",
	},
	[`weapon_smokegrenade`] = {
		["name"] = "weapon_smokegrenade",
		["label"] = "Smoke Grenade",
		["throwable"] = true,
		["durability"] = 0.15,
		["class"] = 5,
		["damagereason"] = "Died",
	},
	[`weapon_ball`] = {
		["name"] = "weapon_ball",
		["label"] = "Ball",
		["throwable"] = true,
		["durability"] = 0.15,
		["ammotype"] = "AMMO_BALL",
        ["damagereason"] = "Died",
	},
	[`weapon_flare`] = {
		["name"] = "weapon_flare",
		["label"] = "Flare pistol",
		["throwable"] = true,
		["durability"] = 0.15,
		["ammotype"] = "AMMO_FLARE",
        ["damagereason"] = "Died",
	},

    -- Miscellaneous
	[`weapon_petrolcan`]            = { ["name"] = "weapon_petrolcan",              ["label"] = "Petrol Can",               ["durability"] = 0.15,  ["ammotype"] = "AMMO_PETROLCAN",        ["damagereason"] = "Died", },
	[`weapon_hazardcan`]            = { ["name"] = "weapon_hazardcan",              ["label"] = "Weapon Hazardcan",         ["durability"] = 0.15,  ["ammotype"] = "AMMO_PETROLCAN",        ["damagereason"] = "Died", },
    [`weapon_fertilizercan`]        = { ["name"] = "weapon_fertilizercan",          ["label"] = "Fertilizer Can",           ["durability"] = 0.15,  ["ammotype"] = "AMMO_FERTILIZERCAN",    ["damagereason"] = "Died", },
	[`gadget_parachute`]            = { ["name"] = "gadget_parachute",              ["label"] = "Parachute",                ["damagereason"] = "Died", },
	[`weapon_fireextinguisher`]     = { ["name"] = "weapon_fireextinguisher",       ["label"] = "Fire Extinguisher",        ["damagereason"] = "Died", },
	[`weapon_barbed_wire`]          = { ["name"] = "weapon_barbed_wire",            ["label"] = "Barbed Wire",              ["damagereason"] = "Prodded", },
	[`weapon_drowning`]             = { ["name"] = "weapon_drowning",               ["label"] = "Drowning",                 ["damagereason"] = "Died", },
	[`weapon_drowning_in_vehicle`]  = { ["name"] = "weapon_drowning_in_vehicle",    ["label"] = "Drowning in a Vehicle",    ["damagereason"] = "Died", },
	[`weapon_bleeding`]             = { ["name"] = "weapon_bleeding",               ["label"] = "Bleeding",                 ["damagereason"] = "Bled out", },
	[`weapon_electric_fence`]       = { ["name"] = "weapon_electric_fence",         ["label"] = "Electric Fence",           ["damagereason"] = "Fried", },
	[`weapon_explosion`]            = { ["name"] = "weapon_explosion",              ["label"] = "Explosion",                ["damagereason"] = "Obliterated", },
	[`weapon_fall`]                 = { ["name"] = "weapon_fall",                   ["label"] = "Fall",                     ["damagereason"] = "Committed suicide", },
	[`weapon_exhaustion`]           = { ["name"] = "weapon_exhaustion",             ["label"] = "Exhaustion",               ["damagereason"] = "Died", },
	[`weapon_hit_by_water_cannon`]  = { ["name"] = "weapon_hit_by_water_cannon",    ["label"] = "Water Cannon",             ["damagereason"] = "Died", },
	[`weapon_rammed_by_car`]        = { ["name"] = "weapon_rammed_by_car",          ["label"] = "Rammed - Vehicle",         ["damagereason"] = "Flattened", },
	[`weapon_run_over_by_car`]      = { ["name"] = "weapon_run_over_by_car",        ["label"] = "Run Over - Vehicle",       ["damagereason"] = "Flattened", },
	[`weapon_heli_crash`]           = { ["name"] = "weapon_heli_crash",             ["label"] = "Heli Crash",               ["damagereason"] = "Helicopter Crash", },
	[`weapon_fire`]                 = { ["name"] = "weapon_fire",                   ["label"] = "Fire",                     ["damagereason"] = "Torched", },

	-- Animals
	[`weapon_animal`] = { ["name"] = "weapon_animal", ["label"] = "Animal", ["damagereason"] = "Mauled", },
    [`weapon_cougar`] = { ["name"] = "weapon_cougar", ["label"] = "Cougar", ["damagereason"] = "Mauled", },
}
