QBShared.AddItems({
	--1of1s
	['WEAPON_MDR2']        = {['name'] = 'WEAPON_MDR2',        ['label'] = 'Desert Tech MDR',	        ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_mdr.png',         ['unique'] = true, ['useable'] = false, ['description'] = 'Desert Tech MDR' },
	['WEAPON_MP9CUSTOM']   = {['name'] = 'WEAPON_MP9CUSTOM',   ['label'] = 'MP9 Custom',	            ['weight'] = 10000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG',   ['image'] = 'weapon_mp9custom.png',   ['unique'] = true, ['useable'] = false, ['description'] = 'TURFS KILLER' },
	['WEAPON_CGMP7']       = {['name'] = 'WEAPON_CGMP7',       ['label'] = 'MP7 Chang Gang',	        ['weight'] = 10000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG',   ['image'] = 'weapon_cgmp7.png',       ['unique'] = true, ['useable'] = false, ['description'] = 'CG' },
	['WEAPON_TONY2XMK2']   = {['name'] = 'WEAPON_TONY2XMK2',   ['label'] = 'Carbine MK2 Custom',        ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_tony2Xmk2.png',   ['unique'] = true, ['useable'] = false, ['description'] = 'Carbine MK2 Custom' },
	['WEAPON_BLIZZHOWA']   = {['name'] = 'WEAPON_BLIZZHOWA',   ['label'] = 'Howa Custom',               ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_blizzhowa.png',   ['unique'] = true, ['useable'] = false, ['description'] = 'Howa Custom' },
	['WEAPON_SPECCYM4']    = {['name'] = 'WEAPON_SPECCYM4',    ['label'] = 'M4 Piggy',                  ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_speccym4.png',    ['unique'] = true, ['useable'] = false, ['description'] = 'M4 Piggy' },
	['WEAPON_DUKECQR']     = {['name'] = 'WEAPON_DUKECQR',     ['label'] = 'Unholy M4',                 ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_dukecqr.png',     ['unique'] = true, ['useable'] = false, ['description'] = 'M4 Unholy' },
	['WEAPON_MC9BVSIL']    = {['name'] = 'WEAPON_MC9BVSIL',    ['label'] = 'MC9 Vsil Chrome And Black', ['weight'] = 10000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG',   ['image'] = 'crashout.png',           ['unique'] = true, ['useable'] = false, ['description'] = 'MC9' },
	['WEAPON_MC9VSIL']     = {['name'] = 'WEAPON_MC9VSIL',     ['label'] = 'MC9 Vsil Chrome',           ['weight'] = 10000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG',   ['image'] = 'crashout.png',           ['unique'] = true, ['useable'] = false, ['description'] = 'MC9' },
	['WEAPON_RAVENBADGER'] = {['name'] = 'WEAPON_RAVENBADGER', ['label'] = 'MOB Honey Badger',          ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_ravenbadger.png', ['unique'] = true, ['useable'] = false, ['description'] = 'MOB Honey Badger' },
	['WEAPON_TONY2XWIENER'] = {['name'] = 'WEAPON_TONY2XWIENER', ['label'] = 'Wiener Gun',              ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_tony2v2.png',     ['unique'] = true, ['useable'] = false, ['description'] = 'I like wiener' },
	['WEAPON_TAYSR']       = {['name'] = 'WEAPON_TAYSR',       ['label'] = 'SR-47 Custom',              ['weight'] = 15000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_taysr.png',       ['unique'] = true, ['useable'] = false, ['description'] = 'TAYSR' },
	['WEAPON_YOSAMP7']     = {['name'] = 'WEAPON_YOSAMP7',     ['label'] = 'MP7 NEON',                  ['weight'] = 10000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_taysr.png',         ['unique'] = true, ['useable'] = false, ['description'] = 'MP7 NEON' },

})