QBShared.AddItems({
    -- Kyros Weapon Mafia
	['weapon_bmarp'] 	     = {['name'] = 'weapon_bmarp', 	       ['label'] = 'BLK MAFIA ARP',     ['weight'] = 5500,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',     ['image'] = 'WEAPON_BMARP.png',          ['unique'] = true,  ['useable'] = false, 	['description'] = ''},
	['weapon_familiasarp']   = {['name'] = 'weapon_familiasarp',   ['label'] = 'FAMILAS ARP',       ['weight'] = 5500,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',     ['image'] = 'WEAPON_FAMILIASARP.png',    ['unique'] = true,  ['useable'] = false, 	['description'] = ''},
	['weapon_cartelarp']     = {['name'] = 'weapon_cartelarp',     ['label'] = 'CARTEL ARP',        ['weight'] = 5500,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',     ['image'] = 'WEAPON_CARTELARP.png',      ['unique'] = true,  ['useable'] = false, 	['description'] = ''},
	['weapon_cripsarp']      = {['name'] = 'weapon_cripsarp', 	   ['label'] = 'CRIPS ARP',         ['weight'] = 5500,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',     ['image'] = 'WEAPON_CRIPSARP.png',       ['unique'] = true,  ['useable'] = false, 	['description'] = ''},
	['weapon_bloodsarp']     = {['name'] = 'weapon_bloodsarp',     ['label'] = 'BLOODS ARP',        ['weight'] = 5500,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE',     ['image'] = 'WEAPON_BLOODSARP.png',      ['unique'] = true,  ['useable'] = false, 	['description'] = ''},
	['weapon_bmglock'] 	     = {['name'] = 'weapon_bmglock',       ['label'] = 'GLOCK41',           ['weight'] = 1700,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',    ['image'] = 'WEAPON_BMGLOCK.png',        ['unique'] = true,  ['useable'] = false,  	['description'] = ''},
	['weapon_familiasglock'] = {['name'] = 'weapon_familiasglock', ['label'] = 'GLOCK41',           ['weight'] = 1700,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',    ['image'] = 'WEAPON_FAMILIASGLOCK.png',  ['unique'] = true,  ['useable'] = false,  	['description'] = ''},
	['weapon_cartelglock'] 	 = {['name'] = 'weapon_cartelglock',   ['label'] = 'GLOCK41',           ['weight'] = 1700, 	  ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',    ['image'] = 'WEAPON_CARTELGLOCK.png',    ['unique'] = true,  ['useable'] = false,  	['description'] = ''},
	['weapon_cripsglock'] 	 = {['name'] = 'weapon_cripsglock',    ['label'] = 'GLOCK41',           ['weight'] = 1700, 	  ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',    ['image'] = 'WEAPON_CRIPSGLOCK.png',     ['unique'] = true,  ['useable'] = false,  	['description'] = ''},
	['weapon_bloodsglock'] 	 = {['name'] = 'weapon_bloodsglock',   ['label'] = 'GLOCK41',           ['weight'] = 1700,    ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL',    ['image'] = 'WEAPON_BLOODSGLOCK.png',    ['unique'] = true,  ['useable'] = false,  	['description'] = ''},

    -- ['at_clip_drum_pistol']  = {['name'] = 'at_clip_drum_pistol',  ['label'] = '50 Round Drum',   ['weight'] = 1250,    ['type'] = 'item',   ['image'] = 'at_clip_drum_pistol.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '50 Round Pistol Drum'},
	['at_clip_clear']        = {['name'] = 'at_clip_clear',        ['label'] = 'Clear Round Mag', ['weight'] = 1000,    ['type'] = 'item',   ['image'] = 'at_clip_clear.png',        ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Clear Weapon Mag'},

    ['at_clip_100_black']    = {['name'] = 'at_clip_100_black',  ['label'] = 'BLK 100R DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_100_black.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '100R Bandana Drum'},
    ['at_clip_100_red']      = {['name'] = 'at_clip_100_red',    ['label'] = 'RED 100R DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_100_red.png',    ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '100R Bandana Drum'},
    ['at_clip_100_blue']     = {['name'] = 'at_clip_100_blue',   ['label'] = 'BLUE 100R DRUM',  ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_100_blue.png',   ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '100R Bandana Drum'},
    ['at_clip_100_green']    = {['name'] = 'at_clip_100_green',  ['label'] = 'GRN 100R DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_100_green.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '100R Bandana Drum'},
    ['at_clip_100_white']    = {['name'] = 'at_clip_100_white',  ['label'] = 'WT 100R DRUM',    ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_100_white.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '100R Bandana Drum'},
    ['at_clip_bandana_black']  = {['name'] = 'at_clip_bandana_black',  ['label'] = 'BLK BANDANA DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_bandana_black.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '60R Bandana Drum'},
    ['at_clip_bandana_red']    = {['name'] = 'at_clip_bandana_red',    ['label'] = 'RED BANDANA DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_bandana_red.png',    ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '60R Bandana Drum'},
    ['at_clip_bandana_blue']   = {['name'] = 'at_clip_bandana_blue',   ['label'] = 'BLUE BANDANA DRUM',  ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_bandana_blue.png',   ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '60R Bandana Drum'},
    ['at_clip_bandana_green']  = {['name'] = 'at_clip_bandana_green',  ['label'] = 'GRN BANDANA DRUM',   ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_bandana_green.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '60R Bandana Drum'},
    ['at_clip_bandana_white']  = {['name'] = 'at_clip_bandana_white',  ['label'] = 'WT BANDANA DRUM',    ['weight'] = 750,    ['type'] = 'item',   ['image'] = 'at_clip_bandana_white.png',  ['unique'] = false,   ['useable'] = true,  ['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = '60R Bandana Drum'},
})
