QBShared.AddItems({
 	--Kyros Weapon Pack Mafia [B]
    weapon_playboyarp            = { name = 'weapon_playboyarp',      label = 'PLAYBOY ARP',        weight = 15000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'WEAPON_PLAYBOYARP.png', unique = true, useable = false, description = '' },
    weapon_hooverarp             = { name = 'weapon_hooverarp',       label = 'HOOVER ARP',         weight = 15000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'WEAPON_HOOVERARP.png', unique = true, useable = false, description = '' },
    weapon_grapearp              = { name = 'weapon_grapearp',        label = 'GRAPE ST. ARP',      weight = 15000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'WEAPON_GRAPEARP.png', unique = true, useable = false, description = '' },
    weapon_latinarp              = { name = 'weapon_latinarp',        label = 'LTN-KINGZ ARP',      weight = 15000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'WEAPON_LATINARP.png', unique = true, useable = false, description = '' },
    weapon_mobarp                = { name = 'weapon_mobarp',          label = 'MOB ARP',            weight = 15000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'WEAPON_MOBARP.png', unique = true, useable = false, description = '' },
    weapon_playboyglock          = { name = 'weapon_playboyglock',    label = 'PLAYBOY GLOCK',      weight = 5000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'WEAPON_PLAYBOYGLOCK.png', unique = true, useable = false, description = '' }, 
    weapon_hooverglock           = { name = 'weapon_hooverglock',     label = 'HOOVER GLOCK',       weight = 5000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'WEAPON_HOOVERGLOCK.png', unique = true, useable = false, description = '' }, 
    weapon_grapeglock            = { name = 'weapon_grapeglock',      label = 'GRAPE ST. GLOCK',    weight = 5000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'WEAPON_GRAPEGLOCK.png', unique = true, useable = false, description = '' }, 
    weapon_latinglock            = { name = 'weapon_latinglock',      label = 'LTN-KINGZ GLOCK',    weight = 5000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'WEAPON_LATINGLOCK.png', unique = true, useable = false, description = '' }, 
    weapon_mobglock              = { name = 'weapon_mobglock',        label = 'MOB GLOCK',          weight = 5000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'WEAPON_MOBGLOCK.png', unique = true, useable = false, description = '' }, 

    -- Extra Attachments aka Custom | Make sure you don't create duplicates
    at_clip_100_yellow           = { name = 'at_clip_100_yellow',      label = 'YEL 100R DRUM',     weight = 1000, type = 'item', image = 'at_clip_100_yellow.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 100 Round Drum' },
    at_clip_100_pink             = { name = 'at_clip_100_pink',        label = 'PNK 100R DRUM',     weight = 1000, type = 'item', image = 'at_clip_100_pink.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 100 Round Drum' },
    at_clip_100_brown            = { name = 'at_clip_100_brown',       label = 'BRN 100R DRUM',     weight = 1000, type = 'item', image = 'at_clip_100_brown.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 100 Round Drum' },
    at_clip_100_orange           = { name = 'at_clip_100_orange',      label = 'ORG 100R DRUM',     weight = 1000, type = 'item', image = 'at_clip_100_orange.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 100 Round Drum' },
    at_clip_100_purple           = { name = 'at_clip_100_purple',      label = 'PUR 100R DRUM',     weight = 1000, type = 'item', image = 'at_clip_100_purple.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 100 Round Drum' },
    at_clip_bandana_pink         = { name = 'at_clip_bandana_pink',    label = 'PNK BANDANA DRUM',  weight = 1000, type = 'item', image = 'at_clip_bandana_pink.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 60 Round Drum' },
    at_clip_bandana_brown        = { name = 'at_clip_bandana_brown',   label = 'BRN BANDANA DRUM',  weight = 1000, type = 'item', image = 'at_clip_bandana_brown.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 60 Round Drum' },
    at_clip_bandana_orange       = { name = 'at_clip_bandana_orange',  label = 'ORG BANDANA DRUM',  weight = 1000, type = 'item', image = 'at_clip_bandana_orange.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 60 Round Drum' },
    at_clip_bandana_yellow       = { name = 'at_clip_bandana_yellow',  label = 'YEL BANDANA DRUM',  weight = 1000, type = 'item', image = 'at_clip_bandana_yellow.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 60 Round Drum' },
    at_clip_bandana_purple       = { name = 'at_clip_bandana_purple',  label = 'PUR BANDANA DRUM',  weight = 1000, type = 'item', image = 'at_clip_bandana_purple.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'A 60 Round Drum' },
})