QBShared.AddWeapons({
    [`WEAPON_L85_CHRISTMAS`] = {
        ["name"] = "WEAPON_L85_CHRISTMAS",
        ["label"] = "L85 CHRISTMAS",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_l85_christmas_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_l85_christmas_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_l85_christmas_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_l85_christmas_scope_small", item = "rifle_scope", },
            ["grip"] = { component = "w_at_l85_christmas_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_NVRIFLE_PURPLE`] = {
        ["name"] = "WEAPON_NVRIFLE_PURPLE",
        ["label"] = "NV Rifle Purple Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_nvrifle_purple_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_nvrifle_purple_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_nvrifle_purple_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_nvrifle_purple_scope_small", item = "rifle_scope", },
            ["sight"] = { component = "w_at_nvrifle_purple_scope_sight", item = "assaultrifle_scope", },
            ["grip"] = { component = "w_at_nvrifle_purple_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_FAMAS_YELLOW`] = {
        ["name"] = "WEAPON_FAMAS_YELLOW",
        ["label"] = "FAMAS Yellow Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_famas_yellow_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_famas_yellow_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_famas_yellow_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_famas_yellow_scope", item = "rifle_scope", },
            ["sight"] = { component = "w_at_famas_yellow_sight", item = "assaultrifle_scope", },
        },
    },
    [`WEAPON_AKPUV2`] = {
        ["name"] = "WEAPON_AKPUV2",
        ["label"] = "AKPUV2 Green Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_akpuv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_akpuv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_akpuv2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_akpuv2_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_akpuv2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_M4A5V2`] = {
        ["name"] = "WEAPON_M4A5V2",
        ["label"] = "M4A5V Cyan Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4a5v2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4a5v2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_m4a5v2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_m4a5v2_scope", item = "rifle_scope", },
            ["sight"] = { component = "w_at_m4a5v2_sight", item = "assaultrifle_scope", },
            ["grip"] = { component = "w_at_m4a5v2_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_FOOLV2_RED`] = {
        ["name"] = "WEAPON_FOOLV2_RED",
        ["label"] = "FOOLV2 Red Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_foolv2_red_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_foolv2_red_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_foolv2_red_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_foolv2_red_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_foolv2_red_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_FOOLV2`] = {
        ["name"] = "WEAPON_FOOLV2",
        ["label"] = "FOOLV2",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_foolv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_foolv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_ar_foolv2_scope", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ar_foolv2_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_ar_foolv2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_GALILARV2`] = {
        ["name"] = "WEAPON_GALILARV2",
        ["label"] = "GALILARV2 Black Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_galilarv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_galilarv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_galilarv2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_galilarv2_scope", item = "rifle_scope", },
        },
    },
    [`WEAPON_HK516V2`] = {
        ["name"] = "WEAPON_HK516V2",
        ["label"] = "HK516V2 Blue Gang",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_hk516v2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_hk516v2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_hk516v2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_hk516v2_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_hk516v2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_HFSMGV2`] = {
        ["name"] = "WEAPON_HFSMGV2",
        ["label"] = "HFSMGV2 ICE Glowing",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_hfsmgv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_hfsmgv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_sb_hfsmgv2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_sb_hfsmgv2_scope", item = "rifle_scope", },
        },
    },
    [`WEAPON_GRU2`] = {
        ["name"] = "WEAPON_GRU2",
        ["label"] = "GRU2 Glowing",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_gru2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_gru2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_gru2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_gru2_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_gru2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_GRAUV2`] = {
        ["name"] = "WEAPON_GRAUV2",
        ["label"] = "GRAUV2 Glowing",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_grauv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_grauv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_grauv2_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_grauv2_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_grauv2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_GYSV2`] = {
        ["name"] = "WEAPON_GYSV2",
        ["label"] = "GYSV2 Glowing",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_gysv2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_gysv2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_gysv2_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_ar_gysv2_grip", item = "rifle_grip", },
        },
    },
    [`WEAPON_NEVAV2`] = {
        ["name"] = "WEAPON_NEVAV2",
        ["label"] = "NEVAV2 (Glows At night)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_nevav2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_nevav2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["sight"] = { component = "w_at_nevav2_sight", item = "assaultrifle_scope", }, --pre equiped
            ["scope"] = { component = "w_at_nevav2_scope", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_nevav2_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_nevav2_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_MODULAR_RIFLE`] = {
        ["name"] = "WEAPON_MODULAR_RIFLE",
        ["label"] = "Modular Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_modular_rifle_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_modular_rifle_mag2", item = "rifle_extendedclip", type = "clip", },
            ["sight"] = { component = "w_at_modular_rifle_scope_sight", item = "assaultrifle_scope", }, --pre equiped
            ["scope"] = { component = "w_at_modular_rifle_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_modular_rifle_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_modular_rifle_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_NVRIFLE`] = {
        ["name"] = "WEAPON_NVRIFLE",
        ["label"] = "NV Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_nvrifle_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_nvrifle_mag2", item = "rifle_extendedclip", type = "clip", },
            ["sight"] = { component = "w_at_nvrifle_scope_sight", item = "assaultrifle_scope", }, --pre equiped
            ["scope"] = { component = "w_at_nvrifle_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_nvrifle_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_nvrifle_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_M4_T_NEON`] = {
        ["name"] = "WEAPON_M4_T_NEON",
        ["label"] = "M4 Tactical Neon",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4_tactical_neon_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4_tactical_neon_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m4_tactical_neon_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_m4_tactical_neon_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_m4_tactical_neon_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_M27S`] = {
        ["name"] = "WEAPON_M27S",
        ["label"] = "M27S",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_pi_m27s_mag1", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_pi_m27s_mag2", item = "pistol_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m27s_scope", item = "pistol_mk2_holoscope", },
            ["flashlight"] = { component = "w_at_m27s_flsh", item = "pistol_flashlight", },
            ["suppressor"] = { component = "w_at_m27s_supp", item = "pistol_suppressor", },
        },
    },
    [`WEAPON_HKUSP`] = {
        ["name"] = "WEAPON_HKUSP",
        ["label"] = "HKUSPistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_pi_hkusp_mag1", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_pi_hkusp_mag2", item = "pistol_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_hkusp_scope", item = "pistol_mk2_holoscope", },
            ["flashlight"] = { component = "w_at_hkusp_flsh", item = "pistol_flashlight", },
            ["suppressor"] = { component = "w_at_hkusp_supp", item = "pistol_suppressor", },
        },
    },
    [`WEAPON_M270D`] = {
        ["name"] = "WEAPON_M270D",
        ["label"] = "M270D",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_m270d_mag1", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_m270d_mag2", item = "pistol_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m270d_scope", item = "pistol_mk2_holoscope", },
            ["flashlight"] = { component = "w_at_m270d_flsh", item = "pistol_flashlight", },
            ["suppressor"] = { component = "w_sb_m270d_supp", item = "pistol_suppressor", },
        },
    },
    [`WEAPON_M4_HALLOWEEN`] = {
        ["name"] = "WEAPON_M4_HALLOWEEN",
        ["label"] = "M4 Halloween",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4_halloween_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4_halloween_mag2", item = "rifle_extendedclip", type = "clip", },
            ["sight"] = { component = "w_at_m4_halloween_sight", item = "assaultrifle_scope", },
            ["scope"] = { component = "w_at_m4_halloween_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_m4_halloween_afgrip", item = "rifle_grip", },
            ["suppressor"] = { component = "w_at_m4_halloween_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_FAMAS`] = {
        ["name"] = "WEAPON_FAMAS",
        ["label"] = "FAMAS",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_famas_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_famas_mag2", item = "rifle_extendedclip", type = "clip", },
            ["sight"] = { component = "w_at_famas_sight", item = "assaultrifle_scope", },
            ["scope"] = { component = "w_at_famas_scope", item = "rifle_grip", },
            ["suppressor"] = { component = "w_at_famas_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_M4_A_W`] = {
        ["name"] = "WEAPON_M4_A_W",
        ["label"] = "M4 Arctric White",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4_a_w_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4_a_w_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m4_w_a_scope", item = "rifle_grip", },
            ["suppressor"] = { component = "w_at_m4_w_a_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_m4_w_a_afgrip", item = "rifle_grip", },
        },
    },
    -- [`WEAPON_L85`] = {
    --     ["name"] = "WEAPON_L85",
    --     ["label"] = "UMP",
    --     ["ammotype"] = "AMMO_RIFLE",
    --     ["type"] = "rifle",
    --      ["class"] = 3,
    --     ["durability"] = 0.14,
    --     ["recoil"] = 0.2,
    --     ["damagereason"] = "Floored",
    --     ["attachments"] = {
    --         ["defaultclip"] = { component = "w_ar_l85_mag1", item = "rifle_defaultclip", type = "clip", },
    --         ["extendedclip"] = { component = "w_ar_l85_mag2", item = "rifle_extendedclip", type = "clip", },
    --         ["scope"] = { component = "w_at_l85_scope_small", item = "rifle_scope", },
    --         ["suppressor"] = { component = "w_at_l85_supp", item = "rifle_suppressor", },
    --         ["grip"] = { component = "w_at_l85_afgrip", item = "rifle_grip", },
    --     },
    -- },
    [`WEAPON_UMP`] = {
        ["name"] = "WEAPON_UMP",
        ["label"] = "UMP",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "smg",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_ump_mag1", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_ump_mag2", item = "smg_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_ump_scope_small", item = "smg_scope", },
            ["suppressor"] = { component = "w_at_ump_supp", item = "smg_suppressor", },
            ["grip"] = { component = "w_at_ump_afgrip", item = "combatpdw_grip", },
        },
    },
    [`WEAPON_MP5`] = {
        ["name"] = "WEAPON_MP5",
        ["label"] = "MP5",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "smg",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_mp5_mag1", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_mp5_mag2", item = "smg_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_mp5_scope", item = "smg_scope", },
            ["suppressor"] = { component = "w_at_mp5_supp", item = "smg_suppressor", },
        },
    },
    [`WEAPON_VECTOR`] = {
        ["name"] = "WEAPON_VECTOR",
        ["label"] = "Vector",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "smg",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_vector_mag1", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_vector_mag2", item = "smg_extendedclip", type = "clip", },
            ["grip"] = { component = "w_sb_vector_afgrip", item = "combatpdw_grip", },
            -- ["iron_sight"] = { component = "w_sb_vector_sight", item = "smg_iron_sight", },
            ["scope"] = { component = "w_sb_vector_scope", item = "smg_scope", },
            ["suppressor"] = { component = "w_sb_vector_supp", item = "smg_suppressor", },
        },
    },
    [`WEAPON_BAS_P_RED`] = {
        ["name"] = "WEAPON_BAS_P_RED",
        ["label"] = "BAS-P Red",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_bas_p_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_bas_p_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_bas_p_scope", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_bas_p_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_bas_p_grip", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_SCEVO`] = {
        ["name"] = "WEAPON_SCEVO",
        ["label"] = "CZ Scorpion EVO",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_cz_sc_evo_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_cz_sc_evo_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_cz_sc_evo_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_cz_sc_evo_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_cz_sc_evo_afgrip", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_R90`] = {
        ["name"] = "WEAPON_R90",
        ["label"] = "R90",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_r20_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_r20_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_r90_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_r90_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_r90_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_M133V3`] = {
        ["name"] = "WEAPON_M133V3",
        ["label"] = "M133V3",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m133_v3_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m133_v3_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_ar_m133_v3_scope", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ar_m133_v3_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_ar_m133_v3_grip", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_GAU_5A`] = {
        ["name"] = "WEAPON_GAU_5A",
        ["label"] = "GAU 5A",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_gau_5a_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_gau_5a_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_gau_5a_mod_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_gau_5a_mod_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_gau_5a_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_M82V2`] = {
        ["name"] = "WEAPON_M82V2",
        ["label"] = "M82V2",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m82v2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m82v2_mag1", item = "rifle_extendedclip", type = "clip", },
            --[[ ["scope"] = { component = "w_at_ar_m82v2_scope", item = "rifle_scope", }, ]] -- already enabled
            ["suppressor"] = { component = "w_at_ar_m82v2_supp", item = "rifle_suppressor", },
            --[[ ["grip"] = { component = "w_at_ar_m82v2_grip", item = "rifle_suppressor", }, ]] -- already enabled
        },
    },
    [`WEAPON_M47V2`] = {
        ["name"] = "WEAPON_M47V2",
        ["label"] = "M47V2",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m47v2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m47v2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["grip"] = { component = "w_at_ar_m47v2_grip", item = "rifle_grip", },
            ["scope"] = { component = "w_at_m47v2_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ar_m47v2_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_HOWAT20`] = {
        ["name"] = "WEAPON_HOWAT20",
        ["label"] = "HOWA T20",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_howat20_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_howat20_mag2", item = "rifle_extendedclip", type = "clip", },
            ["grip"] = { component = "w_at_howat20_afgrip", item = "rifle_grip", },
            -- ["iron_sight"] = { component = "w_at_howat20_iron_sight", item = "assaultrifle_iron_sight", },
            ["scope"] = { component = "w_at_howat20_mod_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_howat20_mod_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_ISYV2`] = {
        ["name"] = "WEAPON_ISYV2",
        ["label"] = "ISYV2",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_isy_v2_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_isy_v2_mag2", item = "rifle_extendedclip", type = "clip", },
            ["grip"] = { component = "w_at_ar_isy_v2_grip", item = "rifle_grip", },
            ["scope"] = { component = "w_at_ar_isy_v2_scope", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ar_isy_v2_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_M4A1_MOD`] = {
        ["name"] = "WEAPON_M4A1_MOD",
        ["label"] = "M4A1 MOD",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4a1_mod_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4a1_mod_mag2", item = "rifle_extendedclip", type = "clip", },
            ["grip"] = { component = "w_atm4a1_mod_afgrip", item = "rifle_grip", },
            -- ["iron_sight"] = { component = "w_at_m4a1_mod_iron_sight", item = "assaultrifle_iron_sight", },
            ["scope"] = { component = "w_at_m4a1_mod_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_m4a1_mod_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_BERYL_762`] = {
        ["name"] = "WEAPON_BERYL_762",
        ["label"] = "Beryl 762",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_beryl_762_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_beryl_762_mag2", item = "rifle_extendedclip", type = "clip", },
            ["grip"] = { component = "w_at_beryl_762_afgrip", item = "rifle_grip", },
            ["scope"] = { component = "w_at_beryl_762_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_beryl_762_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_M4_TACTICAL_RED`] = {
        ["name"] = "WEAPON_M4_TACTICAL_RED",
        ["label"] = "M4 TACTICAL RED",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4_tactical_red_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4_tactical_red_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m4_tactical_red_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_m4_tactical_red_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_m4_tactical_red_supp", item = "rifle_grip", },
        },
    },
    [`WEAPON_AK47_NIGHTWISH`] = {
        ["name"] = "WEAPON_AK47_NIGHTWISH",
        ["label"] = "AK-47 Nightswish",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_ak47_nightwish_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_ak47_nightwish_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_lak47_nightwish_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ak47_nightwish_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_XM7_6_8`] = {
        ["name"] = "WEAPON_XM7_6_8",
        ["label"] = "XM7_6_8 Black",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_xm7_6_8_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_xm7_6_8_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_xm7_6_8_sights_1", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_xm7_6_8_suppressor_1", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_xm7_6_8_afgrip_2", item = "rifle_grip", },
        },
    },
    [`WEAPON_DESERT_EAGLE`]    = {
        ["name"] = "WEAPON_DESERT_EAGLE",
        ["label"] = "Desert Eagle",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_pi_desert_eagle_mag1", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_pi_desert_eagle_mag2", item = "pistol_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_desert_eagle_scope", item = "pistol_mk2_holoscope", },
            ["suppressor"] = { component = "w_at_desert_eagle_supp", item = "pistol_suppressor", },
            ["flashlight"] = { component = "w_at_desert_eagle__flsh", item = "pistol_flashlight", },
        },
    },
    [`WEAPON_SCAR-L`] = {
        ["name"] = "WEAPON_SCAR-L",
        ["label"] = "SCAR-L Black Cammo Edition",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_scar-l_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_scar-l_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_scar-l_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_scar-l_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_scar-l_afgrip", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_AWP_ASIIMOV`] = {
        ["name"] = "WEAPON_AWP_ASIIMOV",
        ["label"] = "AWP Asiimov",
        ["ammotype"] = "AMMO_SNIPER",
        ["type"] = "sniper",
        ["class"] = 5,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Sniped",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sr_heavysniper_mag1", item = "sniper_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sr_heavysniper_mag2", item = "sniper_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_awp_asiimov_scope_large", item = "sniper_scope", },
            ["suppressor"] = { component = "w_at_awp_asiimov_supp", item = "sniper_suppressor", },
        },
    },
    [`WEAPON_P250_ASIIMOV`] = {
        ["name"] = "WEAPON_P250_ASIIMOV",
        ["label"] = "P250 Asiimov",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_pi_p250_asiimov_mag1", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_pi_p250_asiimov_mag2", item = "pistol_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_p250_asiimov_rail", item = "pistol_mk2_holoscope", },
            ["suppressor"] = { component = "w_at_p250_asiimov_supp", item = "pistol_suppressor", },
        },
    },
    [`WEAPON_P20_ASIIMOV`] = {
        ["name"] = "WEAPON_P20_ASIIMOV",
        ["label"] = "P20 Asiimov",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Ended / SMGed / Shot down / Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_p20_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_p20_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_p20_asiimov_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_p20_asiimov_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_AK47_ASIIMOV`] = {
        ["name"] = "WEAPON_AK47_ASIIMOV",
        ["label"] = "AK-47 Asiimov",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_ak47_asiimov_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_ak47_asiimov_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_ak47_asiimov_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ak47_asiimov_supp", item = "rifle_suppressor", },
        },
    },
    [`WEAPON_M4ASIIMOV`] = {
        ["name"] = "WEAPON_M4ASIIMOV",
        ["label"] = "M4 Asiimov",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_m4_asiimov_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_m4_asiimov_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_m4_asiimov_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_m4_asiimov_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_m4_asiimov_grip", item = "grip", },
        },
    },
    [`WEAPON_LMTM4R`] = {
        ["name"] = "WEAPON_LMTM4R",
        ["label"] = "LMTM4R",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_lmtm4r_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_lmtm4r_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_lmtm4r_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_lmtm4r_supp", item = "rifle_suppressor", },
            ["grip"] = { component = "w_at_lmtm4r_afgrip", item = "rifle_grip", },
        },
    },
    [`WEAPON_BULLPUP_SMG`] = {
        ["name"] = "WEAPON_BULLPUP_SMG",
        ["label"] = "Bullpup SMG",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_sb_bullpup_smg_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_sb_bullpup_smg_mag2", item = "rifle_extendedclip", type = "clip", },
            ["scope"] = { component = "w_at_bullpup_smg_scope_small", item = "rifle_scope", },
            ["suppressor"] = { component = "w_at_ar_bullpup_smg_supp", item = "rifle_suppressor", },
            ["flashlight"] = { component = "w_at_bullpup_smg_flsh", item = "rifle_flashlight", },
        },
    },
})
