QBShared.AddWeapons({
	[`weapon_sb4s`] = {
		["name"] = "weapon_sb4s",
		["label"] = "SB-4S",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_sb4s_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_sb4s_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_sb4s_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_sb4s_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_m133`] = {
		["name"] = "weapon_m133",
		["label"] = "M-133",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_m133_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_m133_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_m133_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_m133_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_m133_grip", item = "rifle_grip", },
		},
	},
	[`weapon_neva`] = {
		["name"] = "weapon_neva",
		["label"] = "NEVA",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 3,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_neva_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_neva_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_neva_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_neva_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_neva_grip", item = "rifle_grip", },
		},
	},
	[`weapon_iar`] = {
		["name"] = "weapon_iar",
		["label"] = "Infantry AR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_iar_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_iar_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_iar_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_iar_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_iar_grip", item = "rifle_grip", },
		},
	},
	[`weapon_famasu1`] = {
		["name"] = "weapon_famasu1",
		["label"] = "Famas Underground",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_famasu1_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_famasu1_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_famasu1_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_famasu1_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_grau`] = {
		["name"] = "weapon_grau",
		["label"] = "Grau 5.56",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_grau_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_grau_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_grau_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_grau_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_grau_grip", item = "rifle_grip", },
		},
	},
	[`weapon_jrbak`] = {
		["name"] = "weapon_jrbak",
		["label"] = "JRB-AK",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_jrbak_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_jrbak_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_jrbak_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_jrbak_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_jrbak_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ak47s`] = {
		["name"] = "weapon_ak47s",
		["label"] = "AK-47S",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ak47s_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ak47s_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ak47s_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ak47s_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ak47s_grip", item = "rifle_grip", },
		},
	},
	[`weapon_a15rc`] = {
		["name"] = "weapon_a15rc",
		["label"] = "A15 RC",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {},
	},
	[`weapon_sr47`] = {
		["name"] = "weapon_sr47",
		["label"] = "SR-47",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sr47_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sr47_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sr47_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sr47_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_sr47_grip", item = "rifle_grip", },
		},
	},
	[`weapon_casr`] = {
		["name"] = "weapon_casr",
		["label"] = "CASR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_casr_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_casr_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_casr_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_casr_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_casr_grip", item = "rifle_grip", },
		},
	},
	[`weapon_drh`] = {
		["name"] = "weapon_drh",
		["label"] = "DRH",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_drh_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_drh_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_drh_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_drh_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_drh_grip", item = "rifle_grip", },
		},
	},
	[`weapon_fn42`] = {
		["name"] = "weapon_fn42",
		["label"] = "FN-42",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_fn42_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_fn42_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_fn42_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_fn42_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_m16a3`] = {
		["name"] = "weapon_m16a3",
		["label"] = "M16A3",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_m16a3_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_m16a3_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_m16a3_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_m16a3_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_m16a3_grip", item = "rifle_grip", },
		},
	},
	[`weapon_fmr`] = {
		["name"] = "weapon_fmr",
		["label"] = "FMR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_fmr_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_fmr_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_fmr_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_fmr_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_fmr_grip", item = "rifle_grip", },
		},
	},
	[`weapon_galilar`] = {
		["name"] = "weapon_galilar",
		["label"] = "GALIL AR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_galilar_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_galilar_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_galilar_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_galilar_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_galilar_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ak4k`] = {
		["name"] = "weapon_ak4k",
		["label"] = "AK-4K",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ak4k_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ak4k_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ak4k_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ak4k_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ak4k_grip", item = "rifle_grip", },
		},
	},
	[`weapon_akmkh`] = {
		["name"] = "weapon_akmkh",
		["label"] = "AKM-KH",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_akmkh_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_akmkh_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_akmkh_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_akmkh_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_akmkh_grip", item = "rifle_grip", },
		},
	},
	[`weapon_slr15`] = {
		["name"] = "weapon_slr15",
		["label"] = "SLR-15",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_slr15_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_slr15_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_slr15_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_slr15_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_slr15_grip", item = "rifle_grip", },
		},
	},
	[`weapon_bulldog`] = {
		["name"] = "weapon_bulldog",
		["label"] = "BULLDOG",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_bulldog_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_bulldog_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_bulldog_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_bulldog_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_fn502`] = {
		["name"] = "weapon_fn502",
		["label"] = "FN502",
		["ammotype"] = "AMMO_PISTOL",
		["type"] = "pistol",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 1,
		["damagereason"] = "Blasted",
		["attachments"] = {
			["defaultclip"] = { component = "w_pi_fn502_mag1", item = "pistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_pi_fn502_mag2", item = "pistol_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_at_pi_fn502_supp", item = "pistol_suppressor", },
		},
	},
	[`weapon_sfak`] = {
		["name"] = "weapon_sfak",
		["label"] = "SF-AK",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sfak_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sfak_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sfak_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sfak_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_sfak_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ars`] = {
		["name"] = "weapon_ars",
		["label"] = "ARS",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ars_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ars_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ars_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ars_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ars_grip", item = "rifle_grip", },
		},
	},
	[`weapon_arc15`] = {
		["name"] = "weapon_arc15",
		["label"] = "ARC15",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_arc15_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_arc15_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_arc15_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_arc15_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_arc15_grip", item = "rifle_grip", },
		},
	},
	[`weapon_safak`] = {
		["name"] = "weapon_safak",
		["label"] = "SAFAK",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_safak_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_safak_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_safak_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_safak_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_safak_grip", item = "rifle_grip", },
		},
	},
	[`weapon_howa_2`] = {
		["name"] = "weapon_howa_2",
		["label"] = "HOWA v2",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_howa_2_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_howa_2_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_howa_2_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_howa_2_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_howa_2_grip", item = "rifle_grip", },
		},
	},
	[`weapon_mza`] = {
		["name"] = "weapon_mza",
		["label"] = "MZA",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_mza_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_mza_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_mza_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_mza_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_mza_grip", item = "rifle_grip", },
		},
	},
	[`weapon_sar`] = {
		["name"] = "weapon_sar",
		["label"] = "SAR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sar_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sar_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sar_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sar_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_hfsmg`] = {
		["name"] = "weapon_hfsmg",
		["label"] = "HFSMG",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_hfsmg_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_hfsmg_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_hfsmg_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_hfsmg_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_h2smg`] = {
		["name"] = "weapon_h2smg",
		["label"] = "H2SMG",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_h2smg_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_h2smg_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_h2smg_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_h2smg_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_arma1`] = {
		["name"] = "weapon_arma1",
		["label"] = "ARMA1",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_arma1_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_arma1_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_arma1_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_arma1_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_arma1_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ue4`] = {
		["name"] = "weapon_ue4",
		["label"] = "UE4",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_ue4_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_ue4_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_ue4_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_ue4_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_sfrifle`] = {
		["name"] = "weapon_sfrifle",
		["label"] = "SF-RIFLE",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sfrifle_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sfrifle_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sfrifle_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sfrifle_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_sfcarbinerifle_grip", item = "rifle_grip", },
		},
	},
	[`weapon_sf2`] = {
		["name"] = "weapon_sf2",
		["label"] = "SF-2",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sf2_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sf2_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sf2_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sf2_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_nanite`] = {
		["name"] = "weapon_nanite",
		["label"] = "NANITE",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_nanite_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_nanite_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_nanite_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_nanite_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_nanite_grip", item = "rifle_grip", },
		},
	},
	[`weapon_g36`] = {
		["name"] = "weapon_g36",
		["label"] = "G36",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_g36_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_g36_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_g36_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_g36_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_g36_grip", item = "rifle_grip", },
		},
	},
	[`weapon_sarb`] = {
		["name"] = "weapon_sarb",
		["label"] = "SARB",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_sarb_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_sarb_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_sarb_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_sarb_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_lr300`] = {
		["name"] = "weapon_lr300",
		["label"] = "LR300",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_lr300_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_lr300_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_lr300_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_lr300_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_lr300_grip", item = "rifle_grip", },
		},
	},
	[`weapon_m416p`] = {
		["name"] = "weapon_m416p",
		["label"] = "M416P",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_m416p_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_m416p_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_m416p_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_m416p_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_m416p_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ms32`] = {
		["name"] = "weapon_ms32",
		["label"] = "MS32",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_ms32_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_ms32_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_ms32_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_ms32_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_idw`] = {
		["name"] = "weapon_idw",
		["label"] = "IDW",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["class"] = 2,
		["recoil"] = 0.2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_idw_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_idw_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_idw_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_idw_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_aug`] = {
		["name"] = "weapon_aug",
		["label"] = "AUG",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_aug_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_aug_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_aug_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_aug_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_g3_2`] = {
		["name"] = "weapon_g3_2",
		["label"] = "G3 v2",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_g3_2_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_g3_2_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_g3_2_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_g3_2_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_g3_2_grip", item = "rifle_grip", },
		},
	},
	[`weapon_uzi`] = {
		["name"] = "weapon_uzi",
		["label"] = "UZI",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_uzi_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_uzi_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_uzi_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_uzi_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_sunda`] = {
		["name"] = "weapon_sunda",
		["label"] = "SUNDA",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sunda_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sunda_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sunda_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sunda_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_cfs`] = {
		["name"] = "weapon_cfs",
		["label"] = "CFS",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_cfs_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_cfs_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_cfs_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_cfs_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_cfs_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ak47`] = {
		["name"] = "weapon_ak47",
		["label"] = "AK-47",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ak47_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ak47_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ak47_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ak47_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ak47_grip", item = "rifle_grip", },
		},
	},
	[`weapon_awp`] = {
		["name"] = "weapon_awp",
		["label"] = "AWP",
		["ammotype"] = "AMMO_SNIPER",
		["type"] = "sniper",
		["class"] = 4,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Sniped",
		["attachments"] = {
			["defaultclip"] = { component = "w_sr_awp_mag1", item = "sniperrifle_defaultclip", },
			["suppressor"] = { component = "w_at_sr_awp_supp", item = "sniper_suppressor", },
		},
	},
	[`weapon_groza`] = {
		["name"] = "weapon_groza",
		["label"] = "GROZA",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_groza_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_groza_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_groza_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_groza_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_ditdg`] = {
		["name"] = "weapon_ditdg",
		["label"] = "DITDG",
		["ammotype"] = "AMMO_SNIPER",
		["type"] = "sniper",
		["class"] = 4,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Sniped",
		["attachments"] = {
			["defaultclip"] = { component = "w_sr_ditdg_mag1", item = "sniperrifle_defaultclip", },
			["suppressor"] = { component = "w_at_sr_ditdg_supp", item = "sniper_suppressor", },
		},
	},
	[`weapon_acr`] = {
		["name"] = "weapon_acr",
		["label"] = "ACR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_acr_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_acr_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_acr_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_acr_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_acr_grip", item = "rifle_grip", },
		},
	},
	[`weapon_tar21`] = {
		["name"] = "weapon_tar21",
		["label"] = "TAR21",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_tar21_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_tar21_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_tar21_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_tar21_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_acwr`] = {
		["name"] = "weapon_acwr",
		["label"] = "ACWR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_acwr_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_acwr_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_acwr_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_acwr_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_acwr_grip", item = "rifle_grip", },
		},
	},
	[`weapon_anarchy`] = {
		["name"] = "weapon_anarchy",
		["label"] = "ANARCHY",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_anarchy_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_anarchy_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_anarchy_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_anarchy_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_anarchy_grip", item = "rifle_grip", },
		},
	},
	[`weapon_gk47`] = {
		["name"] = "weapon_gk47",
		["label"] = "GK-47",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_gk47_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_gk47_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_gk47_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_gk47_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_gk47_grip", item = "rifle_grip", },
		},
	},
	[`weapon_far`] = {
		["name"] = "weapon_far",
		["label"] = "FAR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_far_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_far_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_far_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_far_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_far_grip", item = "rifle_grip", },
		},
	},
	[`weapon_heavysmg`] = {
		["name"] = "weapon_heavysmg",
		["label"] = "HEAVY SMG",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_heavysmg_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_heavysmg_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_heavysmg_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_heavysmg_supp", item = "smg_suppressor", },
			["grip"] = { component = "w_at_sb_heavysmg_grip", item = "rifle_grip", },
		},
	},
	[`weapon_gys`] = {
		["name"] = "weapon_gys",
		["label"] = "GYS",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_gys_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_gys_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_gys_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_gys_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_gys_grip", item = "rifle_grip", },
		},
	},
	[`weapon_akpu`] = {
		["name"] = "weapon_akpu",
		["label"] = "AKPU",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_akpu_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_akpu_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_akpu_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_akpu_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_akpu_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ump45`] = {
		["name"] = "weapon_ump45",
		["label"] = "UMP-45",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_ump45_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_ump45_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_ump45_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_ump45_supp", item = "smg_suppressor", },
			["grip"] = { component = "w_at_sb_ump45_grip", item = "rifle_grip", },
		},
	},
	[`weapon_m82`] = {
		["name"] = "weapon_m82",
		["label"] = "M82",
		["ammotype"] = "AMMO_SNIPER",
		["type"] = "sniper",
		["class"] = 4,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_m82_mag1", item = "sniperrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_m82_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_m82_scope", item = "sniper_scope", },
			["suppressor"] = { component = "w_at_ar_m82_supp", item = "sniper_suppressor", },
			["grip"] = { component = "w_at_ar_m82_grip", item = "sniper_grip", },
		},
	},
	[`weapon_sb181`] = {
		["name"] = "weapon_sb181",
		["label"] = "SB181",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_sb181_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_sb181_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_sb181_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_sb181_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_ss2_2`] = {
		["name"] = "weapon_ss2_2",
		["label"] = "SS2 v2",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ss2_2_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ss2_2_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ss2_2_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ss2_2_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ss2_2_grip", item = "rifle_grip", },
		},
	},
	[`weapon_art64`] = {
		["name"] = "weapon_art64",
		["label"] = "AR-T64",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_art64_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_art64_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_art64_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_art64_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_art64_grip", item = "rifle_grip", },
		},
	},
	[`weapon_hfap`] = {
		["name"] = "weapon_hfap",
		["label"] = "HFAP",
		["ammotype"] = "AMMO_PISTOL",
		["type"] = "pistol",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 1,
		["damagereason"] = "Blasted",
		["attachments"] = {
			["defaultclip"] = { component = "w_pi_hfap_mag1", item = "pistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_pi_hfap_mag2", item = "pistol_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_at_pi_hfap_supp", item = "pistol_suppressor", },
		},
	},
	[`weapon_sm237`] = {
		["name"] = "weapon_sm237",
		["label"] = "SM-237",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_sm237_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_sm237_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_sm237_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_sm237_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_sm237_grip", item = "rifle_grip", },
		},
	},
	[`weapon_r99`] = {
		["name"] = "weapon_r99",
		["label"] = "R99",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_r99_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_r99_mag2", item = "smg_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_at_ar_va030_supp", item = "smg_suppressor", }, -- test pls dont push unless needed
		},
	},
	[`weapon_cz75`] = {
		["name"] = "weapon_cz75",
		["label"] = "CZ75",
		["ammotype"] = "AMMO_PISTOL",
		["type"] = "pistol",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Blasted",
		["attachments"] = {
			["defaultclip"] = { component = "w_pi_cz75_mag1", item = "pistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_pi_cz75_mag2", item = "pistol_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_at_pi_cz75_supp", item = "pistol_suppressor", },
		},
	},
	[`weapon_pl14`] = {
		["name"] = "weapon_pl14",
		["label"] = "PL14",
		["ammotype"] = "AMMO_PISTOL",
		["type"] = "pistol",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 1,
		["damagereason"] = "Blasted",
		["attachments"] = {
			["defaultclip"] = { component = "w_pi_pl14_mag1", item = "pistol_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_pi_pl14_mag2", item = "pistol_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_at_pi_pl14_supp", item = "pistol_suppressor", },
		},
	},
	[`weapon_va030`] = {
		["name"] = "weapon_va030",
		["label"] = "VA030",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_va030_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_va030_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_va030_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_ar_va030_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_ar727`] = {
		["name"] = "weapon_ar727",
		["label"] = "AR-727",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 3,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ar727_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ar727_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ar727_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ar727_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ar727_grip", item = "rifle_grip", },
		},
	},
	[`weapon_scarsc`] = {
		["name"] = "weapon_scarsc",
		["label"] = "SCARSC",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 3,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_scarsc_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_scarsc_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_scarsc_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_scarsc_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_scarsc_grip", item = "rifle_grip", },
		},
	},
	[`weapon_ar121`] = {
		["name"] = "weapon_ar121",
		["label"] = "AR-121",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ar121_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ar121_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ar121_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ar121_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ar121_grip", item = "rifle_grip", },
		},
	},
	[`weapon_smg1311`] = {
		["name"] = "weapon_smg1311",
		["label"] = "SMG1311",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_smg1311_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_smg1311_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_smg1311_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_smg1311_supp", item = "smg_suppressor", },
		},
	},
	[`weapon_dcs`] = {
		["name"] = "weapon_dcs",
		["label"] = "DCS",
		["ammotype"] = "AMMO_SHOTGUN",
		["type"] = "amotgun",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Pulverized",
		["attachments"] = {
			["defaultclip"] = { component = "w_sg_dcs_mag1", item = "assaultshotgun_defaultclip", type = "clip", },
			["grip"] = { component = "w_at_sg_dcs_grip", item = "rifle_grip", },
			["suppressor"] = { component = "w_at_sg_dcs_supp", item = "shotgun_suppressor", },
		},
	},
	[`weapon_anr15`] = {
		["name"] = "weapon_anr15",
		["label"] = "ANR15",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 3,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_anr15_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_anr15_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_anr15_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_anr15_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_anr15_grip", item = "rifle_grip", },
		},
	},
	[`weapon_owshotgun`] = {
		["name"] = "weapon_owshotgun",
		["label"] = "OWSHOTGUN",
		["ammotype"] = "AMMO_SHOTGUN",
		["type"] = "amotgun",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Pulverized",
	},
	[`weapon_anm4`] = {
		["name"] = "weapon_anm4",
		["label"] = "ANM4",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_anm4_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_anm4_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_anm4_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_anm4_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_anm4_grip", item = "rifle_grip", },
		},
	},
	[`weapon_gvandal`] = {
		["name"] = "weapon_gvandal",
		["label"] = "GVANDAL",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_gvandal_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_gvandal_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_gvandal_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_gvandal_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_gvandal_grip", item = "rifle_grip", },
		},
	},
	[`weapon_limpid`] = {
		["name"] = "weapon_limpid",
		["label"] = "LIMPID",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["class"] = 3,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_limpid_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_limpid_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_limpid_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_limpid_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_limpid_grip", item = "rifle_grip", },
		},
	},
	[`weapon_akbg`] = {
		["name"] = "weapon_akbg",
		["label"] = "AKBG",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_akbg_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_akbg_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_akbg_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_akbg_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_akbg_grip", item = "rifle_grip", },
		},
	},
	[`weapon_pasmg`] = {
		["name"] = "weapon_pasmg",
		["label"] = "PASMG",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_pasmg_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_pasmg_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_pasmg_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_pasmg_supp", item = "smg_suppressor", type = "silencer" },
		},
	},
	[`weapon_mx4`] = {
		["name"] = "weapon_mx4",
		["label"] = "MX4",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_mx4_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_mx4_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_mx4_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_mx4_supp", item = "smg_suppressor", },
			["grip"] = { component = "w_at_sb_mx4_grip", item = "rifle_grip", },
		},
	},
	[`weapon_truvelo`] = {
		["name"] = "weapon_truvelo",
		["label"] = "TRUVELO",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_truvelo_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_truvelo_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_truvelo_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_truvelo_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_truvelo_grip", item = "rifle_grip", },
		},
	},
	[`weapon_autosmg`] = {
		["name"] = "weapon_autosmg",
		["label"] = "AUTOSMG",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {},
	},
	[`weapon_benellim4`] = {
		["name"] = "weapon_benellim4",
		["label"] = "BENELLIM4",
		["ammotype"] = "AMMO_SHOTGUN",
		["type"] = "amotgun",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Pulverized",
		["attachments"] = {
			["suppressor"] = { component = "w_at_sg_benellim4_supp", item = "shotgun_suppressor", },
		},
	},
	[`weapon_l85`] = {
		["name"] = "weapon_l85",
		["label"] = "L85",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_l85_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_l85_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_l85_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_l85_supp", item = "rifle_suppressor", },
		},
	},
	[`weapon_book`] = {
		["name"] = "weapon_book",
		["label"] = "BOOK",
		["throwable"] = true,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Died",
	},
	[`weapon_brick`] = {
		["name"] = "weapon_brick",
		["label"] = "BRICK",
		["throwable"] = true,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Died",
	},
	[`weapon_highboot`] = {
		["name"] = "weapon_highboot",
		["label"] = "HIGHBOOT",
		["throwable"] = true,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Died",
	},
	[`weapon_dks501`] = {
		["name"] = "weapon_dks501",
		["label"] = "DKS501",
		["ammotype"] = "AMMO_SNIPER",
		["type"] = "sniper",
		["class"] = 4,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_dks501_mag1", item = "sniperrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_dks501_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_dks501_scope", item = "sniper_scope", },
			["suppressor"] = { component = "w_at_ar_dks501_supp", item = "sniper_suppressor", },
			["grip"] = { component = "w_at_ar_dks501_grip", item = "sniper_grip", },
		},
	},
	[`weapon_energyknife`] = {
		["name"] = "weapon_energyknife",
		["label"] = "Energy Knife",
		["type"] = "melee",
		["durability"] = 0.14,
		["class"] = "B",
		["recoil"] = 0.2,
		["damagereason"] = "Stabbed",
	},
	[`weapon_karambit`] = {
		["name"] = "weapon_karambit",
		["label"] = "Karambit",
		["type"] = "melee",
		["durability"] = 0.14,
		["class"] = "B",
		["recoil"] = 0.2,
		["damagereason"] = "Stabbed",
	},
	[`weapon_scifw`] = {
		["name"] = "weapon_scifw",
		["label"] = "SCIFW",
		["ammotype"] = "AMMO_SNIPER",
		["type"] = "sniper",
		["class"] = 4,
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_scifw_mag1", item = "sniperrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_scifw_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_scifw_scope", item = "sniper_scope", },
			["suppressor"] = { component = "w_at_ar_scifw_supp", item = "sniper_suppressor", },
			["grip"] = { component = "w_at_ar_scifw_grip", item = "sniper_grip", },
		},
	},
	[`weapon_ssr56`] = {
		["name"] = "weapon_ssr56",
		["label"] = "SSR56",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_ssr56_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_ssr56_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_ssr56_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_ssr56_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_ssr56_grip", item = "rifle_grip", },
		},
	},
	[`weapon_lgwii`] = {
		["name"] = "weapon_lgwii",
		["label"] = "Lewis Gun WWII",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_lgwii_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_lgwii_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["grip"] = { component = "w_at_ar_lgwii_grip", item = "rifle_grip", },
		},
	},
	[`weapon_m90s`] = {
		["name"] = "weapon_m90s",
		["label"] = "M90S",
		["ammotype"] = "AMMO_SHOTGUN",
		["type"] = "amotgun",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["damagereason"] = "Pulverized",
		["attachments"] = {
			["defaultclip"] = { component = "w_sg_m90s_mag1", item = "assaultshotgun_defaultclip", type = "clip", },
		},
	},
	[`weapon_an94_2`] = {
		["name"] = "weapon_an94_2",
		["label"] = "AN94_2",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["class"] = 3,
		["recoil"] = 0.2,
		["damagereason"] = "Floored",
		["attachments"] = {
			["defaultclip"] = { component = "w_ar_an94_2_mag1", item = "assaultrifle_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_ar_an94_2_mag2", item = "assaultrifle_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_ar_an94_2_scope", item = "rifle_scope", },
			["suppressor"] = { component = "w_at_ar_an94_2_supp", item = "rifle_suppressor", },
			["grip"] = { component = "w_at_ar_an94_2_grip", item = "rifle_grip", },
		},
	},
	[`weapon_smg9`] = {
		["name"] = "weapon_smg9",
		["label"] = "SMG9",
		["ammotype"] = "AMMO_SMG",
		["type"] = "smg",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 2,
		["damagereason"] = "Riddled",
		["attachments"] = {
			["defaultclip"] = { component = "w_sb_smg9_mag1", item = "smg_defaultclip", type = "clip", },
			["extendedclip"] = { component = "w_sb_smg9_mag2", item = "smg_extendedclip", type = "clip", },
			["scope"] = { component = "w_at_sb_smg9_scope", item = "smg_scope", },
			["suppressor"] = { component = "w_at_sb_smg9_supp", item = "smg_suppressor", },
			["grip"] = { component = "w_at_sb_smg9_grip", item = "rifle_grip", },
		},
	},
	[`weapon_knr`] = {
		["name"] = "weapon_knr",
		["label"] = "KNR",
		["ammotype"] = "AMMO_RIFLE",
		["type"] = "rifle",
		["durability"] = 0.14,
		["recoil"] = 0.2,
		["class"] = 1,
		["damagereason"] = "Blasted",
		["attachments"] = {
			["defaultclip"] = { component = "w_pi_knr_mag1", item = "pistol_defaultclip", type = "clip", },
			["suppressor"] = { component = "w_at_pi_knr_comp", item = "pistol_suppressor", },
			["flashlight"] = { component = "w_at_pi_knr_flsh", item = "pistol_flashlight", },
			["scope"] = { component = "w_at_pi_knr_scope", item = "rifle_scope", },
		},
	},
})
