QBShared.AddWeapons({
    [`weapon_akt`] = {
        ["name"] = "weapon_akt",
        ["label"] = "AKT",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.10,
        ["recoil"] = 0.2,
        ["damagereason"] = "Rifled",
        ["attachments"] = {
            ["defaultclip"] = { component = "w_ar_akt_mag1", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "w_ar_akt_mag2", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_at_ar_akt_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_at_ar_akt_scope", item = "rifle_scope", },
            ["grip"] = { component = "w_at_ar_akt_grip", item = "rifle_grip", },
        },
    },
    [`weapon_sniper_chromium`] = {
		["name"] = "weapon_sniper_chromium",
		["label"] = "SNIPER Chromium Purple-Pink Edition",
		["type"] = "Sniper",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Ended / Snipered / Shot down / Floored",
		["recoil"] = 0.2,
		["durability"] = 0.10,
		["class"] = 4,
		["attachments"] = {
			["extendedclip"] = { component = "w_sr_sniper_chromium_mag2", item = "sniper_extendedclip", type = "clip", },
			["suppressor"] = { component = "w_ar_sniper_chromium_supp", item = "sniper_suppressor", },
		},
	},
	[`weapon_m9_p_chromium`] = {
        ["name"] = "weapon_m9_p_chromium",
        ["label"] = "M9 Pistol Chromium Purple-Pink Edition",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.10,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["extendedclip"] = { component = "w_pi_m9_chromium_mag2", item = "pistol_extendedclip", type = "clip", },
			["flashlight"] = { component = "w_at_m9_chromium_flashlight", item = "pistol_flashlight" },
			["scope"] = { component = "w_at_m9_chromium_holo", item = "rifle_scope" },
			["suppressor"] = { component = "w_at_m9_chromium_supp", item = "pistol_suppressor", type = "silencer" },
        },
    },
    [`weapon_arc15_mini`] = {
        ["name"] = "weapon_arc15_mini",
        ["label"] = "ARC15 MINI Chromium Purple-Pink Edition",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.10,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["extendedclip"] = { component = "w_ar_arc15_mini_chromium_boxmag", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "w_ar_arc15_mini_chromium_supp", item = "rifle_suppressor", },
            ["scope"] = { component = "w_ar_arc15_mini_chromium_holo", item = "rifle_scope", },
            ["grip"] = { component = "w_ar_arc15_mini_chromium_grip", item = "rifle_grip", },
        },
    },
})
