QBShared.AddWeapons({
[`WEAPON_MDR2`] = {
        ["name"] = "WEAPON_MDR2",
        ["label"] = "MDR",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MDR2_CLIP_08", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_MDR2_SUPP_02", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_MDR2_SCOPE_01", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_MDR2_GRIP", item = "rifle_grip", },
        },
},
[`WEAPON_MP9CUSTOM`] = {
        ["name"] = "WEAPON_MP9CUSTOM",
        ["label"] = "MP9 Custom",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "SMG",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_AT_MP9CUSTOM_SUPP_02", item = "smg_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SB_MP9CUSTOM_CLIP1", item = "smg_suppressor", },
        },
},
[`WEAPON_CGMP7`] = {
        ["name"] = "WEAPON_CGMP7",
        ["label"] = "MP7 Chang Gang",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "SMG",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_CGMP7_MAG1", item = "smg_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_PI_SUPP", item = "smg_suppressor", },
  },
},
[`WEAPON_TONY2XMK2`] = {
        ["name"] = "WEAPON_TONY2XMK2",
        ["label"] = "Carbine MK2 Custom",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TONY2XMK2_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_TONY2XMK2_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_BLIZZHOWA`] = {
        ["name"] = "WEAPON_BLIZZHOWA",
        ["label"] = "Howa Custom",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_BLIZZHOWA_MAG1", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_SPECCYM4`] = {
        ["name"] = "WEAPON_SPECCYM4",
        ["label"] = "M4 Piggy",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_SPECCYM4_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_SPECCYM4_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_DUKECQR`] = {
        ["name"] = "WEAPON_DUKECQR",
        ["label"] = "M4 Unholy",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_DUKECQR_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_DUKECQR_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_MC9BVSIL`] = {
        ["name"] = "WEAPON_MC9BVSIL",
        ["label"] = "MC9 Vsil Chrome And Black",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "SMG",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PL_SMG_MC9V1_CHAIN_T_CLIP_01", item = "smg_defaultclip", type = "clip", },
  },
},
[`WEAPON_MC9VSIL`] = {
        ["name"] = "WEAPON_MC9VSIL",
        ["label"] = "MC9 Vsil Chrome",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "SMG",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PL_SMG_MC9V1_CHAIN_EMI_CLIP_01", item = "smg_defaultclip", type = "clip", },
  },
},
[`WEAPON_RAVENBADGER`] = {
        ["name"] = "WEAPON_RAVENBADGER",
        ["label"] = "MOB Honey Badger",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "RIFLE",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_RAVENBADGER_CLIP", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_RAVENBADGER_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_TONY2XWIENER`] = {
        ["name"] = "WEAPON_TONY2XWIENER",
        ["label"] = "Wiener Gun",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TONY2XWIENER_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_TONY2XWIENER_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_TAYSR`] = {
        ["name"] = "WEAPON_TAYSR",
        ["label"] = "SR-47 Custom",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "RIFLE",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TAYSR_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_TAYSR_SUPP", item = "rifle_suppressor", },
  },
},
[`WEAPON_YOSAMP7`] = {
        ["name"] = "WEAPON_YOSAMP7",
        ["label"] = "MP7 NEON",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "SMG",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_YOSAMP7_CLIP_01", item = "smg_defaultclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_YOSAMP7_SUPP", item = "smg_suppressor", },
  },
}, 

})