QBShared.AddWeapons({
	[`weapon_glock19x`] = {
        ['name'] = 'weapon_glock19x',
        ['label'] = 'G19X XL',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK19X_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK19X_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['drum'] = { component = 'COMPONENT_GLOCK19X_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
            ['100roundmag'] = { component = 'COMPONENT_GLOCK19X_CLIP_04', item = 'at_clip_100_pistol', type = 'clip', },
        }
    },
	[`weapon_glock19`] = {
        ['name'] = 'weapon_glock19',
        ['label'] = 'GLOCK 19',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK19_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK19_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['drum'] = { component = 'COMPONENT_GLOCK19_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
        }
    },
	[`weapon_glock40`] = {
        ['name'] = 'weapon_glock40',
        ['label'] = 'GLOCK 40',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK40_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK40_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['drum'] = { component = 'COMPONENT_GLOCK40_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
            ['100roundmag'] = { component = 'COMPONENT_GLOCK40_CLIP_04', item = 'at_clip_100_pistol', type = 'clip', },
        }
    },
	[`weapon_glock40s`] = {
        ['name'] = 'weapon_glock40s',
        ['label'] = 'GLOCK 40 SWITCH',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK40S_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK40S_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['drum'] = { component = 'COMPONENT_GLOCK40S_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
            ["100roundmag"] = { component = "COMPONENT_GLOCK40S_CLIP_04", item = "at_clip_100_pistol", type = "clip", },
        }
    },
	[`weapon_ddm4v5`] = {
        ['name'] = 'weapon_ddm4v5',
        ['label'] = 'DDM4V5',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_DDM4V5_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
        }
    },
	[`weapon_mpx`] = {
        ['name'] = 'weapon_mpx',
        ['label'] = 'MPX',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_SMG',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_MPX_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
        }
    },
	[`weapon_pd509`] = {
        ['name'] = 'weapon_pd509',
        ['label'] = 'PD 509',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_COMBATPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_aps`] = {
        ['name'] = 'weapon_aps',
        ['label'] = 'STECHKIN APS',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_APPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_APPISTOL_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
        }
    },
	[`weapon_ppk`] = {
        ['name'] = 'weapon_ppk',
        ['label'] = 'WALTHER PPK',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_SNSPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_pitviper`] = {
        ['name'] = 'weapon_pitviper',
        ['label'] = 'JW4 PIT VIPER',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_PITVIPER_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_barp`] = {
        ['name'] = 'weapon_barp',
        ['label'] = 'BANSHEE ARP-9',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_BARP_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_BARP_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['flashlight'] = { component = 'COMPONENT_AT_AR_BARPFLSH', item = 'pistol_flashlight', },
        }
    },
	[`weapon_rdp`] = {
        ['name'] = 'weapon_rdp',
        ['label'] = 'BHELLCAT RDP',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_PISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['scope'] = { component = 'COMPONENT_AT_PI_RAIL', item = 'smg_scope', },
        }
    },
	[`weapon_lok`] = {
        ['name'] = 'weapon_lok',
        ['label'] = 'M-LOK AR 15',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_LOK_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
            ['grip'] = { component = 'COMPONENT_AT_AR_LOKAFGRIP', item = 'rifle_grip', },
        }
    },
	[`weapon_plr`] = {
        ['name'] = 'weapon_plr',
        ['label'] = 'PLR-16',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_PLR_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_PLR_CLIP_02', item = 'assaultrifle_extendedclip', type = 'clip', },
            ['grip'] = { component = 'COMPONENT_AT_AR_PLRAFGRIP', item = 'rifle_grip', },
        }
    },
	[`weapon_xds9`] = {
        ['name'] = 'weapon_xds9',
        ['label'] = 'XDS9',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_XDS9_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_XDS9_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
        }
    },
	[`weapon_pps`] = {
        ['name'] = 'weapon_pps',
        ['label'] = 'WALTHER PPS',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_SNSPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_xdme`] = {
        ['name'] = 'weapon_xdme',
        ['label'] = 'XDM ELITE',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_COMBATPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_sp`] = {
        ['name'] = 'weapon_sp',
        ['label'] = 'FN-15 PISTOL',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_SP_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
        }
    },
	[`weapon_glock17s`] = {
        ['name'] = 'weapon_glock17s',
        ['label'] = 'GLOCK 17 SWITCH',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK17_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK17_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
        }
    },
	[`weapon_glock18c`] = {
        ['name'] = 'weapon_glock18c',
        ['label'] = 'GLOCK 18C',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK18C_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_GLOCK18C_CLIP_02', item = 'pistol_extendedclip', type = 'clip', },
            ['drum'] = { component = 'COMPONENT_GLOCK18C_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
        }
    },
	[`weapon_glock19s`] = {
        ['name'] = 'weapon_glock19s',
        ['label'] = 'GLOCK 19 SWITCH',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK19S_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_arpistol`] = {
        ['name'] = 'weapon_arpistol',
        ['label'] = 'TATIC ARP 9MM',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_ARPISTOL_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_ARPISTOL_BOXMAG', item = 'pistol_extendedclip', type = 'clip', },
            ['scope'] = { component = 'COMPONENT_AT_ARPISTOLSCOPE_MEDIUM', item = 'smg_scope', },
        }
    },
	[`weapon_glock26s`] = {
        ['name'] = 'weapon_glock26s',
        ['label'] = 'GLOCK 26 SWITCH',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_GLOCK26S_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
        }
    },
	[`weapon_grenades`] = {
        ['name'] = 'weapon_grenades',
        ['label'] = 'GRENADE SNIPER',
        ['weapontype'] = 'Heavy Weapons',
        ['ammotype'] = 'AMMO_GRENADELAUNCHER',
        ["type"] = "grenadelauncher",
        ["class"] = 5,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Obliterated',
    },
	[`weapon_m32s`] = {
        ['name'] = 'weapon_m32s',
        ['label'] = 'M32 SMOKE GL',
        ['weapontype'] = 'Heavy Weapons',
        ['ammotype'] = 'AMMO_GRENADELAUNCHER',
        ["type"] = "grenadelauncher",
        ["class"] = 5,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Obliterated',
    },
	[`weapon_microdraco`] = {
        ['name'] = 'weapon_microdraco',
        ['label'] = 'MICRO DRACO',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_MICRODRACO_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
        }
    },
	[`weapon_ruger57`] = {
        ['name'] = 'weapon_ruger57',
        ['label'] = 'RUGER 57',
        ['weapontype'] = 'Pistol',
        ['ammotype'] = 'AMMO_PISTOL',
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Blasted',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_RUGER57_CLIP_01', item = 'pistol_defaultclip', type = 'clip', },
            ['flashlight'] = { component = 'COMPONENT_AT_PI_RUGER57FLSH', item = 'pistol_flashlight', },
        }
    },
	[`weapon_mk18`] = {
        ['name'] = 'weapon_mk18',
        ['label'] = 'MK18 MOD 1',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_MK18_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
        }
    },
	[`weapon_680`] = {
        ['name'] = 'weapon_680',
        ['label'] = 'MODEL 680',
        ['weapontype'] = 'Shotgun',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ["type"] = "shotgun",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ['damagereason'] = 'Pulverized',
    },
	[`weapon_ziptie`] = {
        ['name'] = 'weapon_ziptie',
        ['label'] = 'ZIP TIE M4A1',
        ['weapontype'] = 'Assault Rifle',
        ['ammotype'] = 'AMMO_RIFLE',
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.10,
        ["recoil"] = 0.1,
        ['damagereason'] = 'Floored',
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_ZIPTIE_CLIP_01', item = 'assaultrifle_defaultclip', type = 'clip', },
            ['extendedclip'] = { component = 'COMPONENT_ZIPTIE_BOXMAG', item = 'assaultrifle_extendedclip', type = 'clip', },
            ['suppressor'] = { component = 'COMPONENT_AT_AR_ZIPTIE_SUPP', item = 'rifle_suppressor', },
        }
    },
})
