QBShared.AddWeapons({
    -- Kyros Weapon Pack V1
    [`weapon_draco`] = {
        name = 'weapon_draco',
        label = 'MINI DRACO',
        type = 'rifle',
        ammotype = 'AMMO_RIFLE',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Ended / Rifled / Shot down / Floored',
        attachments = {},
    },
    [`weapon_sig516`] = {
        name = 'weapon_sig516',
        label = 'SIG 516',
        type = 'rifle',
        ammotype = 'AMMO_RIFLE',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Ended / Rifled / Shot down / Floored',
        attachments = {},
    },
    [`weapon_nsr`] = {
        name = 'weapon_nsr',
        label = 'NSR',
        type = 'rifle',
        ammotype = 'AMMO_RIFLE',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Ended / Rifled / Shot down / Floored',
        attachments = {
            ["flashlight"] = { component = "COMPONENT_AT_AR_NSR_FLSH", item = "rifle_flashlight", type = "flashlight", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_NSR_SUPP", item = "rifle_suppressor", type = "suppressor", },
        },
    },
    [`weapon_gardone`] = {
        name = 'weapon_gardone',
        label = 'GARDONE',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_GARDONE_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_GARDONE_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_fnx`] = {
        name = 'weapon_fnx',
        label = 'FNX .45',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {},
    },
    [`weapon_g30`] = {
        name = 'weapon_g30',
        label = 'GLOCK 30',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {},
    },
    [`weapon_tec9`] = {
        name = 'weapon_tec9',
        label = 'TEC-9',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_TEC9_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_TEC9_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_p226`] = {
        name = 'weapon_p226',
        label = 'P226R',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_P226_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_P226_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_g18c`] = {
        name = 'weapon_g18c',
        label = 'GLOCK 18C',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_G18C_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_G18C_CLIP_02", item = "pistol_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_AT_G18C_FLSH", item = "pistol_flashlight", type = "flashlight", },
        },
    },
    [`weapon_g17`] = {
        name = 'weapon_g17',
        label = 'GLOCK 17',
        type = 'pistol',
        ammotype = 'AMMO_PISTOL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_G17_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_G17_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_barrett`] = {
        name = 'weapon_barrett',
        label = 'BARRETT 50',
        type = 'Sniper Rifle',
        ammotype = 'AMMO_SNIPER',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Sniped / Picked off / Scoped',
        attachments = {
            ["scope"] = { component = "COMPONENT_AT_BARRETT50_SCOPE_MAX", item = "sniper_scope", type = "scope", },
        },
    },
    -- [`weapon_mp5`] = {
    --     name = 'weapon_mp5',
    --     label = 'MP5',
    --     type = 'smg',
    --     ammotype = 'AMMO_SMG',
    --     durability = 0.15,
    --     recoil = 0.2,
    --     damagereason = 'Riddled / Drilled / Finished / Submachine Gunned',
    --     attachments = {},
    -- },
    [`weapon_mac`] = {
        name = 'weapon_mac',
        label = 'MAC-10',
        type = 'smg',
        ammotype = 'AMMO_SMG',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Riddled / Drilled / Finished / Submachine Gunned',
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_MAC_CLIP_01", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MAC_CLIP_02", item = "smg_extendedclip", type = "clip", },
        },
    },
    [`weapon_m870`] = {
        name = 'weapon_m870',
        label = 'REMINGTON M870',
        type = 'shotgun',
        ammotype = 'AMMO_SHOTGUN',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Devastated / Pulverized / Shotgunned',
        attachments = {},
    },
    [`weapon_paintball`] = {
        name = 'weapon_paintball',
        label = 'PAINT BALL GUN',
        type = 'smg',
        ammotype = 'AMMO_PAINTBALL',
        durability = 0.15,
        recoil = 0.2,
        damagereason = 'Splat / Popped / Finished / Lit up',
        attachments = {},
    },
})