QBShared.AddWeapons({
    --Kyros Weapon Pack V2
	[`weapon_heraarms`] = {
        name = "weapon_heraarms",
        label = "HERA ARMS",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_HERAARMS_CLIP_01", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_HERAARMS_BOXMAG", item = "rifle_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_AT_AR_HERAARMS_FLSH", item = "rifle_flashlight", },
            ["scope"] = { component = "COMPONENT_AT_SCOPE_HERAARMS_MEDIUM", item = "rifle_scope", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_HERAARMS_SUPP", item = "rifle_suppressor", },
            ["grip"] = { component = "COMPONENT_AT_AR_HERAARMS_AFGRIP", item = "rifle_grip", },
        },
    },
	[`weapon_sa80`] = {
        name = "weapon_sa80",
        label = "SA80",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_honeybadger`] = {
        name = "weapon_honeybadger",
        label = "HONEYBADGER",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["suppressor"] = { component = "COMPONENT_AT_AR_HONEYBADGER_SUPP", item = "rifle_suppressor", },
        },
    },
	[`weapon_m45a1`] = {
        name = "weapon_m45a1",
        label = "COLT M45A1",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_CJ_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_CJ_CLIP_02", item = "rifle_extendedclip", type = "clip" },
        },
    },
	[`weapon_ace`] = {
        name = "weapon_ace",
        label = "IWI Galil ACE",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ACE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ACE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
        },
    },
	-- [`weapon_ak47`] = {
    --     name = "weapon_ak47",
    --     label = "AK-47",
    --     type = "rifle",
    --      class = 3,
    --     ammotype = "AMMO_RIFLE",
    --     durability = 0.15,
    --     recoil = 0.2,
    --     damagereason = "Floored",
    --     attachments = {},
    -- },
	[`weapon_m14`] = {
        name = "weapon_m14",
        label = "M14",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_rpk16`] = {
        name = "weapon_rpk16",
        label = "RPK-16",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_m249`] = {
        name = "weapon_m249",
        label = "M249",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_m1918a2`] = {
        name = "weapon_m1918a2",
        label = "M1918A2",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_lvoca`] = {
        name = "weapon_lvoca",
        label = "LVOA-C",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["grip"] = { component = "COMPONENT_AT_AR_LVOCA_AFGRIP", item = "rifle_grip", },
        },
    },
	[`weapon_g36k`] = {
        name = "weapon_g36k",
        label = "G36K",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_G36K_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_G36K_CLIP_02", item = "rifle_extendedclip", type = "clip" },
        },
    },
	[`weapon_xm4`] = {
        name = "weapon_xm4",
        label = "COLT XM4",
        type = "rifle",
        class = 3,
        ammotype = "AMMO_RIFLE",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Floored",
        attachments = {},
    },
	[`weapon_beretta`] = {
        name = "weapon_beretta",
        label = "BERETTA",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_python`] = {
        name = "weapon_python",
        label = "PYTHON",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_maxim9`] = {
        name = "weapon_maxim9",
        label = "MAXIM 9",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {
            ["suppressor"] = { component = "COMPONENT_AT_AR_MAXIM9_SUPP", item = "pistol_suppressor", },
        },
    },
	[`weapon_cj`] = {
        name = "weapon_cj",
        label = "COLT JUNIOR",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_CJ_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_CJ_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
	[`weapon_snub`] = {
        name = "weapon_snub",
        label = "SNUBNOSE REVOLVER",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_laugoarms`] = {
        name = "weapon_laugoarms",
        label = "LAUGO ARMS",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_b93r`] = {
        name = "weapon_b93r",
        label = "Beretta 93R",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_B93R_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_B93R_CLIP_02", item = "pistol_extendedclip", type = "clip" },
        },
    },
	[`weapon_makarov`] = {
        name = "weapon_makarov",
        label = "MAKAROV",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_MAKAROV_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_MAKAROV_CLIP_02", item = "pistol_extendedclip", type = "clip" },
        },
    },
	-- [`weapon_fn502`] = {
    --     name = "weapon_fn502",
    --     label = "FN 502",
    --     type = "pistol",
    --     class = 1,
    --     ammotype = "AMMO_PISTOL",
    --     durability = 0.15,
    --     recoil = 0.2,
    --     damagereason = "Blasted",
    --     attachments = {
    --         ["suppressor"] = { component = "COMPONENT_AT_AR_FN502_SUPP", item = "pistol_suppressor", },
    --     },
    -- },
	[`weapon_1911`] = {
        name = "weapon_1911",
        label = "1911",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_659`] = {
        name = "weapon_659",
        label = "S&W M659",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_659_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_659_CLIP_02", item = "pistol_extendedclip", type = "clip" },
        },
    },
	[`weapon_m906`] = {
        name = "weapon_m906",
        label = "ZORAKI M906",
        type = "pistol",
        class = 1,
        ammotype = "AMMO_PISTOL",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Blasted",
        attachments = {},
    },
	[`weapon_magpulpdr`] = {
        name = "weapon_magpulpdr",
        label = "MAGPUL PDR",
        type = "smg",
        class = 2,
        ammotype = "AMMO_SMG",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Riddled",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_MAGPULPDR_CLIP_01", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MAGPULPDR_CLIP_02", item = "smg_extendedclip", type = "clip", },
        },
    },
	[`weapon_mp9`] = {
        name = "weapon_mp9",
        label = "B&T MP9",
        type = "smg",
        class = 2,
        ammotype = "AMMO_SMG",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Riddled",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_MP9_CLIP_01", item = "smg_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_MP9_CLIP_02", item = "smg_extendedclip", type = "clip" },
            ["grip"] = { component = "COMPONENT_AT_MP9_SCOPE_MACRO", item = "combatpdw_grip", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_MP9_SUPP", item = "smg_suppressor", },
        },
    },
	[`weapon_m32`] = {
        name = "weapon_m32",
        label = "M32 GL",
        type = "special",
        ammotype = "AMMO_GRENADELAUNCHER",
        class = 5,
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Obliterated",
        attachments = {},
    },
	[`weapon_bryson`] = {
        name = "weapon_bryson",
        label = "BRYSON 890",
        type = "shotgun",
        class = 3,
        ammotype = "AMMO_SHOTGUN",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Pulverized",
        attachments = {},
    },
	[`weapon_aa12`] = {
        name = "weapon_aa12",
        label = "AA-12",
        type = "shotgun",
        ammotype = "AMMO_SHOTGUN",
        class = 3,
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Pulverized",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AA12_CLIP_01", item = "shotgun_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AA12_CLIP_02", item = "shotgun_extendedclip", type = "clip" },
        },
    },
})
