QBShared.AddWeapons({
    --Kyros Weapon Pack AirSoft
	[`weapon_airsoftak47`] = {
        name = "weapon_airsoftak47",
        label = "AIRSOFT AK47",
        weapontype = "Assault Rifle",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftg36c`] = {
        name = "weapon_airsoftg36c",
        label = "AIRSOFT G36C",
        weapontype = "Assault Rifle",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftglock`] = {
        name = "weapon_airsoftglock",
        label = "AIRSOFT GLOCK",
        weapontype = "Pistol",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftm14`] = {
        name = "weapon_airsoftm14",
        label = "AIRSOFT M14",
        weapontype = "Sniper Rifle",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftm249`] = {
        name = "weapon_airsoftm249",
        label = "AIRSOFT M249",
        weapontype = "Light Machine Gun",
        type = "machinegun",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftuzi`] = {
        name = "weapon_airsoftuzi",
        label = "AIRSOFT UZI",
        weapontype = "Submachine Gun",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftmp5`] = {
        name = "weapon_airsoftmp5",
        label = "AIRSOFT MP5",
        weapontype = "Submachine Gun",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftr870`] = {
        name = "weapon_airsoftr870",
        label = "AIRSOFT R870",
        weapontype = "Shotgun",
        type = "shotgun",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftdraco`] = {
        name = "weapon_airsoftdraco",
        label = "AIRSOFT DRACO",
        weapontype = "Assault Rifle",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftscar`] = {
        name = "weapon_airsoftscar",
        label = "AIRSOFT SCAR",
        weapontype = "Assault Rifle",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftaug`] = {
        name = "weapon_airsoftaug",
        label = "AIRSOFT AUG",
        weapontype = "Submachine Gun",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftxd`] = {
        name = "weapon_airsoftxd",
        label = "AIRSOFT XD UM",
        weapontype = "Pistol",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftm4a1`] = {
        name = "weapon_airsoftm4a1",
        label = "AIRSOFT M4A1 UM",
        weapontype = "Assault Rifle",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftfn57`] = {
        name = "weapon_airsoftfn57",
        label = "AIRSOFT FN57",
        weapontype = "Pistol",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
	[`weapon_airsoftp90`] = {
        name = "weapon_airsoftp90",
        label = "AIRSOFT P90",
        weapontype = "Sniper Rifle",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        ammotype = "AMMO_AIRSOFT",
        damagereason = "Bust a BB in ya ass",
        attachments = {},
    },
})