QBShared.AddWeapons({
    --Kyros Weapon Pack V5
    [`weapon_bar15`] = {
        ["name"] = "weapon_bar15",
        ["label"] = "AR-15",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["flashlight"] = { component = "COMPONENT_AT_AR_BAR15_FLSH", item = "rifle_flashlight", },
            ["scope"] = { component = "COMPONENT_AT_BAR15_SCOPE_MEDIUM", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_AT_AR_BAR15_AFGRIP", item = "rifle_grip", },
        },
    },
    [`weapon_blackarp`] = {
        ["name"] = "weapon_blackarp",
        ["label"] = "BLACK ARP",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {},
    },
    [`weapon_bscar`] = {
        ["name"] = "weapon_bscar",
        ["label"] = "BLACK SCAR",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_BSCAR_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_BSCAR_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
        },
    },
    [`weapon_thompson`] = {
        ["name"] = "weapon_thompson",
        ["label"] = "BLACK THOMPSON",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_THOMPSON_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_THOMPSON_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
        },
    },
    [`weapon_dmk18`] = {
        ["name"] = "weapon_dmk18",
        ["label"] = "DESERET MK18",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["flashlight"] = { component = "COMPONENT_AT_AR_DMK18_FLSH", item = "rifle_flashlight", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_DMK18_SUPP", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_AT_DMK18_SCOPE_MEDIUM", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_AT_AR_DMK18_AFGRIP", item = "rifle_grip", },
        },
    },
    [`weapon_lbtarp`] = {
        ["name"] = "weapon_lbtarp",
        ["label"] = "LB TAN ARP",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_LBTANARP_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_LBTANARP_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
            ["drum"] = { component = "COMPONENT_LBTANARP_CLIP_03", item = "assaultrifle_drum", type = "clip", },
        },
    },
    [`weapon_ram7`] = {
        ["name"] = "weapon_ram7",
        ["label"] = "RAM-7",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_RAM7_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_RAM7_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
        },
    },
    [`weapon_redarp`] = {
        ["name"] = "weapon_redarp",
        ["label"] = "RED DRAG ARP",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_REDARP_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_REDARP_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
            ["drum"] = { component = "COMPONENT_REDARP_CLIP_03", item = "assaultrifle_drum", type = "clip", },
        },
    },
    [`weapon_redm4a1`] = {
        ["name"] = "weapon_redm4a1",
        ["label"] = "RED DRAG M4A1",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_REDM4A1_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_REDM4A1_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_AT_AR_REDM4A1_SUPP", item = "rifle_suppressor", },
        },
    },
    [`weapon_tarp`] = {
        ["name"] = "weapon_tarp",
        ["label"] = "TAN ARP",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TANARP_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_TANARP_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
            ["drum"] = { component = "COMPONENT_TANARP_CLIP_03", item = "assaultrifle_drum", type = "clip", },
        },
    },
    [`weapon_woarp`] = {
        ["name"] = "weapon_woarp",
        ["label"] = "WHITE OUT ARP",
        ["weapontype"] = "Assault Rifle",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_WOARP_CLIP_01", item = "assaultrifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_WOARP_CLIP_02", item = "assaultrifle_extendedclip", type = "clip", },
            ["drum"] = { component = "COMPONENT_WOARP_CLIP_03", item = "assaultrifle_drum", type = "clip", },
        },
    },
    [`weapon_blueglocks`] = {
        ["name"] = "weapon_blueglocks",
        ["label"] = "BLUE GLOCK SWITCH",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_BLUEGLOCKS_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_BLUEGLOCKS_CLIP_02", item = "pistol_extendedclip", type = "clip", },
            ["100roundmag"] = { component = "COMPONENT_BLUEGLOCKS_CLIP_04", item = "at_clip_100_pistol", type = "clip", },
            ["clearroundmag"] = { component = "COMPONENT_BLUEGLOCKS_CLIP_05", item = "at_clip_clear", type = "clip", },
            ['drum'] = { component = 'COMPONENT_BLUEGLOCKS_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },

        },
    },
    [`weapon_fn57`] = {
        ["name"] = "weapon_fn57",
        ["label"] = "FN Five-seveN",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_glock21`] = {
        ["name"] = "weapon_glock21",
        ["label"] = "GLOCK 21",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_glock41`] = {
        ["name"] = "weapon_glock41",
        ["label"] = "GLOCK 41",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_GLOCK41_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_GLOCK41_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_glockbeams`] = {
        ["name"] = "weapon_glockbeams",
        ["label"] = "GLOCK BEAM SWITCH",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_GLOCKBEAMS_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_GLOCKBEAMS_CLIP_02", item = "pistol_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_AT_PI_GLOCKBEAMS_FLSH", item = "pistol_flashlight", },
            ["100roundmag"] = { component = "COMPONENT_GLOCKBEAMS_CLIP_04", item = "at_clip_100_pistol", type = "clip", },
            ["clearroundmag"] = { component = "COMPONENT_GLOCKBEAMS_CLIP_05", item = "at_clip_clear", type =  "clip", },
            ['drum'] = { component = 'COMPONENT_GLOCKBEAMS_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },
        },
    },
    [`weapon_p30l`] = {
        ["name"] = "weapon_p30l",
        ["label"] = "H&K P30L",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_illglock17`] = {
        ["name"] = "weapon_illglock17",
        ["label"] = "ILLEGAL GLOCK 17",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_ILLGLOCK17_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_ILLGLOCK17_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_mgglock`] = {
        ["name"] = "weapon_mgglock",
        ["label"] = "MG GLOCK",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MGGLOCK_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MGGLOCK_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_midasglock`] = {
        ["name"] = "weapon_midasglock",
        ["label"] = "MIDAS GLOCK",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MIDASGLOCK_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MIDASGLOCK_CLIP_02", item = "pistol_extendedclip", type = "clip", },
            ["100roundmag"] = { component = "COMPONENT_MIDASGLOCK_CLIP_04", item = "at_clip_100_pistol", type = "clip", },
            ["clearroundmag"] = { component = "COMPONENT_MIDASGLOCK_CLIP_05", item = "at_clip_clear", type = "clip", },
            ['drum'] = { component = 'COMPONENT_MIDASGLOCK_CLIP_03', item = 'at_clip_drum_pistol', type = 'clip', },

        },
    },
    [`weapon_p210`] = {
        ["name"] = "weapon_p210",
        ["label"] = "P210 CARRY",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_sr40`] = {
        ["name"] = "weapon_sr40",
        ["label"] = "RUGER SR40",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_t1911`] = {
        ["name"] = "weapon_t1911",
        ["label"] = "TAN 1911",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {},
    },
    [`weapon_tglock19`] = {
        ["name"] = "weapon_tglock19",
        ["label"] = "TAN G19",
        ["weapontype"] = "Pistol",
        ["ammotype"] = "AMMO_PISTOL",
        ["type"] = "pistol",
        ["class"] = 1,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Blasted",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TGLOCK19_CLIP_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_TGLOCK19_CLIP_02", item = "pistol_extendedclip", type = "clip", },
        },
    },
    [`weapon_axe`] = {
        ["name"] = "weapon_axe",
        ["label"] = "AXE",
        ["weapontype"] = "Melee",
        ["ammotype"] = nil,
        ["type"] = "melee",
        ["class"] = "C",
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Chopped",
        ["attachments"] = {},
    },
    [`weapon_chair`] = {
        ["name"] = "weapon_chair",
        ["label"] = "BRAWL CHAIR",
        ["weapontype"] = "Melee",
        ["ammotype"] = nil,
        ["type"] = "melee",
        ["class"] = "C",
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Whacked",
        ["attachments"] = {},
    },
    [`weapon_krissvector`] = {
        ["name"] = "weapon_krissvector",
        ["label"] = "KRISS VECTOR",
        ["weapontype"] = "Submachine Gun",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "smg",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Riddled",
        ["attachments"] = {},
    },
    [`weapon_tec9s`] = {
        ["name"] = "weapon_tec9s",
        ["label"] = "TEC 9 W STRAP",
        ["weapontype"] = "Submachine Gun",
        ["ammotype"] = "AMMO_SMG",
        ["type"] = "smg",
        ["class"] = 2,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Riddled",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_TEC9S_CLIP_01", item = "smg_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_TEC9S_CLIP_02", item = "smg_extendedclip", type = "clip", },
        },
    },
    [`weapon_m500`] = {
        ["name"] = "weapon_m500",
        ["label"] = "MOSSBERG 500",
        ["weapontype"] = "Shotgun",
        ["ammotype"] = "AMMO_SHOTGUN",
        ["type"] = "shotgun",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Pulverized",
        ["attachments"] = {},
    },
    [`weapon_r590`] = {
        ["name"] = "weapon_r590",
        ["label"] = "REMINGTON 590",
        ["weapontype"] = "Shotgun",
        ["ammotype"] = "AMMO_SHOTGUN",
        ["type"] = "shotgun",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Pulverized",
        ["attachments"] = {},
    },
})
