QBShared.AddWeapons({
    [`weapon_midasgun`] = {
        name = "weapon_midasgun",
        label = "Midas Gun",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_ASSAULTRIFLE_CLIP_03", item = "rifle_drum", type = "clip" },
            ["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "rifle_flashlight", type = "flashlight" },
            ["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "rifle_scope", type = "scope" },
            ["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
            ["grip"] = { component = "COMPONENT_AT_AR_AFGRIP", item = "rifle_grip", type = "grip" },
        }
    },
    [`weapon_redl`] = {
        name = "weapon_redl",
        label = "AK-REDL",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_akorus`] = {
        name = "weapon_akorus",
        label = "AKORUS",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKORUS_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKORUS_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKORUS_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKORUS_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_militarm4`] = {
        name = "weapon_militarm4",
        label = "MILITARM4",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M4LEOSHOP_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_M4LEOSHOP_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_M4LEOSHOP_CLIP_03", item = "rifle_drum", type = "clip" },
            ["scope"] = { component = "COMPONENT_AT_M4LEOSHOP_MEDIUM", item = "rifle_scope", type = "scope" },
            ["suppressor"] = { component = "COMPONENT_AT_M4LEOSHOP_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_goldm`] = {
        name = "weapon_goldm",
        label = "GOLDM",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_GOLDM_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_GOLDM_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_GOLDM_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_GOLDM_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_predator`] = {
        name = "weapon_predator",
        label = "PREDATOR",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_PREDATOR_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_PREDATOR_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["box"] = { component = "COMPONENT_PREDATOR_CLIP_03" },
            ["scope"] = { component = "COMPONENT_AT_PREDATOR_MEDIUM", item = "rifle_scope", type = "scope" },
            ["suppressor"] = { component = "COMPONENT_AT_PREDATOR_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
            ["grip"] = { component = "COMPONENT_AT_PREDATOR_AFGRIP", item = "rifle_grip", type = "grip" },
        }
    },
    [`weapon_kinetic`] = {
        name = "weapon_kinetic",
        label = "KINETIC",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_KINETIC_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_KINETIC_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["box"] = { component = "COMPONENT_KINETIC_CLIP_03" },
            ["scope"] = { component = "COMPONENT_AT_KINETIC_MEDIUM", item = "rifle_scope", type = "scope" },
            ["flashlight"] = { component = "COMPONENT_AT_KINETIC_FLSH", item = "rifle_flashlight", type = "flashlight" },
            ["suppressor"] = { component = "COMPONENT_AT_KINETIC_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
            ["grip"] = { component = "COMPONENT_AT_KINETIC_AFGRIP", item = "rifle_grip", type = "grip" },
        }
    },
    -- [`weapon_scarsc`] = {
    --     name = "weapon_scarsc",
    --     label = "SCARSC",
    --     ammotype = "AMMO_SMG",
    --     type = "smg",
    --     durability = 0.15,
    --     recoil = 0.2,
    --     damagereason = "Ended / Shot down / Floored",
    --     attachments = {
    --         ["defaultclip"] = { component = "COMPONENT_SCARSC_CLIP_01", item = "smg_defaultclip", type = "clip" },
    --         ["extendedclip"] = { component = "COMPONENT_SCARSC_CLIP_02", item = "smg_extendedclip", type = "clip" },
    --         -- ["box"] = { component = "COMPONENT_SCARSC_CLIP_03" },
    --         ["scope"] = { component = "COMPONENT_AT_SCOPE_SCARSC", item = "smg_scope", type = "scope" },
    --         ["flashlight"] = { component = "COMPONENT_AT_SCARSC_FLSH", item = "smg_flashlight", type = "flashlight" },
    --         ["suppressor"] = { component = "COMPONENT_AT_SCARSC_SUPP_02", item = "smg_suppressor", type = "suppressor" },
    --         ["grip"] = { component = "COMPONENT_AT_SCARSC_AFGRIP", item = "smg_grip", type = "grip" },
    --     }
    -- },
    [`weapon_tec9m`] = {
        name = "weapon_tec9m",
        label = "TEC9M",
        ammotype = "AMMO_SMG",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_TEC9M_CLIP_01", item = "smg_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_TEC9M_CLIP_02", item = "smg_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_TEC9M_CLIP_03", item = "smg_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_TEC9M_SUPP", item = "smg_suppressor", type = "suppressor" },
        }
    },
    [`weapon_tec9mf`] = {
        name = "weapon_tec9mf",
        label = "TEC9MF",
        ammotype = "AMMO_SMG",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_TEC9MF_CLIP_01", item = "smg_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_TEC9MF_CLIP_02", item = "smg_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_TEC9MF_CLIP_03", item = "smg_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_TEC9MF_SUPP", item = "smg_suppressor", type = "suppressor" },
        }
    },
    [`weapon_tec9mb`] = {
        name = "weapon_tec9mb",
        label = "TEC9MB",
        ammotype = "AMMO_SMG",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_TEC9MB_CLIP_01", item = "smg_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_TEC9MB_CLIP_02", item = "smg_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_TEC9MB_CLIP_03", item = "smg_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_TEC9MB_SUPP", item = "smg_suppressor", type = "suppressor" },
        }
    },
    [`weapon_blastak`] = {
        name = "weapon_blastak",
        label = "BLASTAK",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_BLASTAK_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_BLASTAK_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_BLASTAK_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_BLASTAK_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_blastm4`] = {
        name = "weapon_blastm4",
        label = "BLASTM4",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_BLASTM4_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_BLASTM4_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_BLASTM4_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_BLASTM4_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_sig550`] = {
        name = "weapon_sig550",
        label = "SIG550",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SG550_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SG550_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_SG550_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SG550_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_blacksniper`] = {
        name = "weapon_blacksniper",
        label = "BLACKSNIPER",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_BLACKLEOSHOP_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_BLACKLEOSHOP_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["scope"] = { component = "COMPONENT_AT_BLACKLEOSHOP_MAX", item = "sniper_scope", type = "scope" },
            -- ["scope_advanced"] = { component = "COMPONENT_AT_BLACKLEOSHOP_MAX", item = "sniper_scope_advanced", type = "scope" },
            ["suppressor"] = { component = "COMPONENT_AT_AR_SUPPBLACKLEOSHOP_02", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_sovereign`] = {
        name = "weapon_sovereign",
        label = "SOVEREIGN",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SOVEREIGN_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SOVEREIGN_CLIP_02", item = "pistol_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SOVEREIGN_SUPP", item = "pistol_suppressor", type = "suppressor" },
        }
    },
    [`weapon_glock17`] = {
        name = "weapon_glock17",
        label = "GLOCK17",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_COMBATPISTOL_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_GLOCKLEOSHOP_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["flashlight"] = { component = "COMPONENT_AT_GLOCKLEOSHOP_FLSH", item = "rifle_flashlight", type = "flashlight" },
            ["suppressor"] = { component = "COMPONENT_AT_GLOCKLEOSHOP_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_coachgun`] = {
        name = "weapon_coachgun",
        label = "COACHGUN",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_COACHGUN_CLIP_01", item = "rifle_defaultclip", type = "clip" },
        }
    },
    [`weapon_shotgunk`] = {
        name = "weapon_shotgunk",
        label = "SHOTGUNK",
        ammotype = "AMMO_SHOTGUN",
        type = "shotgun",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["flashlight"] = { component = "COMPONENT_AT_AR_SHOTGUNKLEOSHOPFLSH", item = "shotgun_flashlight", type = "flashlight" },
            ["suppressor"] = { component = "COMPONENT_AT_SHOTGUNK_SUPP", item = "shotgun_suppressor", type = "suppressor" },
        }
    },
    [`weapon_vsco`] = {
        name = "weapon_vsco",
        label = "VSCO",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_VSCO_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_VSCO_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_VSCO_CLIP_03", item = "sniper_drum", type = "clip" },
            ["scope"] = { component = "COMPONENT_AT_VSCO_MAX", item = "sniper_scope", type = "scope" },
            -- ["scope_advanced"] = { component = "COMPONENT_AT_VSCO_MAX2" },
            ["suppressor"] = { component = "COMPONENT_AT_AR_VSCO_02", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_blueriot`] = {
        name = "weapon_blueriot",
        label = "BLUERIOT",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_BLUERIOT_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_BLUERIOT_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_BLUERIOT_SUPP_02", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_ancient`] = {
        name = "weapon_ancient",
        label = "ANCIENT",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ANCIENT_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ANCIENT_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_ANCIENT_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_ANCIENT_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_snake`] = {
        name = "weapon_snake",
        label = "SNAKE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SNAKE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SNAKE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_SNAKE_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SNAKE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_hell`] = {
        name = "weapon_hell",
        label = "HELL",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_HELL_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_HELL_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_HELL_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_HELL_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_oblivion`] = {
        name = "weapon_oblivion",
        label = "OBLIVION",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_OBLIVION_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_OBLIVION_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_OBLIVION_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_OBLIVION_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_alien`] = {
        name = "weapon_alien",
        label = "ALIEN",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ALIEN_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ALIEN_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_ALIEN_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_ALIENAR_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_midgard`] = {
        name = "weapon_midgard",
        label = "MIDGARD",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_MIDGARD_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_MIDGARD_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["box"] = { component = "COMPONENT_MIDGARD_CLIP_03" },
            ["scope"] = { component = "COMPONENT_AT_MIDGARDSCOPE_MEDIUM", item = "rifle_scope", type = "scope" },
            ["suppressor"] = { component = "COMPONENT_AT_MIDGARDAR_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_chainsaw`] = {
        name = "weapon_chainsaw",
        label = "CHAINSAW",
        ammotype = nil,
        type = "heavy",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_specialhammer`] = {
        name = "weapon_specialhammer",
        label = "SPECIALHAMMER",
        ammotype = nil,
        type = "melee",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_penis`] = {
        name = "weapon_penis",
        label = "PENIS",
        ammotype = nil,
        type = "melee",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_maze`] = {
        name = "weapon_maze",
        label = "MAZE",
        ammotype = nil,
        type = "melee",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_revolvervamp`] = {
        name = "weapon_revolvervamp",
        label = "REVOLVERVAMP",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_guard`] = {
        name = "weapon_guard",
        label = "AK_GUARD",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_GUARD_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_GUARD_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_GUARD_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_GUARD_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    -- [`weapon_grau`] = {
    --     name = "weapon_grau",
    --     label = "GRAU",
    --     ammotype = "AMMO_RIFLE",
    --     type = "rifle",
    --     durability = 0.15,
    --     recoil = 0.2,
    --     damagereason = "Ended / Shot down / Floored",
    --     attachments = {
    --         ["defaultclip"] = { component = "COMPONENT_GRAU_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    --         ["extendedclip"] = { component = "COMPONENT_GRAU_CLIP_02", item = "rifle_extendedclip", type = "clip" },            
    --         ["drum"] = { component = "COMPONENT_GRAU_CLIP_03", item = "rifle_drum", type = "clip" },
    --         -- ["drum"] = { component = "COMPONENT_GRAU_CLIP_03_V2" },
    --         -- ["drum"] = { component = "COMPONENT_GRAU_CLIP_03_V3" },
    --         ["flashlight"] = { component = "COMPONENT_AT_GRAU_AR_FLSH", item = "rifle_flashlight", type = "flashlight" },
    --         ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_MEDIUM", item = "rifle_scope", type = "scope" },
    --         -- ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_MEDIUM2" },
    --         -- ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_MEDIUM3" },
    --         -- ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_LONG" },
    --         -- ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_LONGX" },
    --         ["suppressor"] = { component = "COMPONENT_AT_AR_GRAU_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
    --         -- ["suppressor"] = { component = "COMPONENT_AT_AR_GRAU_SUPP_03" },
    --         -- ["suppressor"] = { component = "COMPONENT_AT_AR_GRAU_SUPP_04" },
    --         ["stock"] = { component = "COMPONENT_GRAU_STOCK", item = "rifle_stock", type = "stock" },
    --         -- ["stock"] = { component = "COMPONENT_GRAU_STOCK2" },
    --         -- ["stock"] = { component = "COMPONENT_GRAU_STOCK3" },
    --         -- ["stock"] = { component = "COMPONENT_GRAU_STOCK4" },
    --         -- ["stock"] = { component = "COMPONENT_GRAU_STOCK1_V2" },
    --         -- ["stock"] = { component = "COMPONENT_GRAU_STOCK2_V3" },
    --         ["grip"] = { component = "COMPONENT_AT_GRAU_AR_AFGRIP", item = "rifle_grip", type = "grip" },
    --         -- ["grip"] = { component = "COMPONENT_AT_GRAU_AR_AFGRIP2" },
    --         -- ["grip"] = { component = "COMPONENT_AT_GRAU_AR_AFGRIP3" },
    --         -- ["grip"] = { component = "COMPONENT_AT_GRAU_AR_AFGRIP4" },
    --         ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V5", item = "rifle_luxary_finish", type = "luxary_finish" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V3" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V4" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V2F" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V3F" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_GRAU_VARMOD_V2" }
    --     }
    -- },
    [`weapon_scar17`] = {
        name = "weapon_scar17",
        label = "SCAR17",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SCAR17_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SCAR17_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["extendedclip"] = { component = "COMPONENT_SCAR17_V2_CLIP_02" },
            -- ["extendedclip"] = { component = "COMPONENT_SCAR17_V3_CLIP_02" },
            ["drum"] = { component = "COMPONENT_SCAR17_CLIP_03", item = "rifle_drum", type = "clip" },
            -- ["drum"] = { component = "COMPONENT_SCAR17_V2_CLIP_03" },
            -- ["drum"] = { component = "COMPONENT_SCAR17_V3_CLIP_03" },
            -- ["drum"] = { component = "COMPONENT_SCAR17_V4_CLIP_03" },
            ["flashlight"] = { component = "COMPONENT_AT_SCAR17_FLSH", item = "rifle_flashlight", type = "flashlight" },
            ["scope"] = { component = "COMPONENT_AT_SCAR17_MEDIUM", item = "rifle_scope", type = "scope" },
            -- ["scope"] = { component = "COMPONENT_AT_SCAR17_V3_MEDIUM" },
            -- ["scope"] = { component = "COMPONENT_AT_GRAU_SCOPE_MEDIUM3" },
            ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_03" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_04" },
            ["stock"] = { component = "COMPONENT_SCAR17_STOCK", item = "rifle_stock", type = "stock" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_STOCK2" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_STOCK4" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_STOCK5" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_V2_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_V3_STOCK" },
            -- ["stock"] = { component = "COMPONENT_SCAR17_V4_STOCK5" },
            ["luxary_finish"] = { component = "COMPONENT_SCAR17_VARMOD_V2", item = "rifle_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCAR17_VARMOD_V3" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCAR17_VARMOD_SMALL" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCAR17_VARMOD_V4" }
        }
    },
    [`weapon_uzils`] = {
        name = "weapon_uzils",
        label = "UZI",
        ammotype = "AMMO_SMG",
        type = "smg",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_UZILS_CLIP_01", item = "smg_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_02", item = "smg_extendedclip", type = "clip" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_03" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_04" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_01v4" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_02v18" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_02v13" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_03v3" },
            -- ["extendedclip"] = { component = "COMPONENT_UZILS_CLIP_03v16" },
            ["suppressor"] = { component = "COMPONENT_AT_UZILS_SUPP_02", item = "smg_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_UZILS_SUPP_02v3" },
            ["stock"] = { component = "COMPONENT_UZILS_STOCK", item = "smg_stock", type = "stock" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCK2" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCK4" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCK3v3" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCKv13" },
            -- ["stock"] = { component = "COMPONENT_UZILS_STOCKv18" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARREL" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARREL2" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARREL3" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARREL4" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARRELv18" },
            -- ["stock"] = { component = "COMPONENT_UZILS_BARREL4v13" },
            ["luxary_finish"] = { component = "COMPONENT_UZILS_VARMOD_V3", item = "smg_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_UZILS_VARMOD_V4" },
            -- ["luxary_finish"] = { component = "COMPONENT_UZILS_VARMOD_V13" },
            -- ["luxary_finish"] = { component = "COMPONENT_UZILS_VARMOD_V16" },
            -- ["luxary_finish"] = { component = "COMPONENT_UZILS_VARMOD_V18" }
        }
    },
    [`weapon_m19`] = {
        name = "weapon_m19",
        label = "M19",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M19_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            -- ["defaultclip"] = { component = "COMPONENT_M19_CLIP_01V2" },
            ["extendedclip"] = { component = "COMPONENT_M19_CLIP_02", item = "pistol_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_M19_CLIP_03", item = "pistol_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_PI_M19_SUPP2", item = "pistol_suppressor", type = "suppressor" },
            ["luxary_finish"] = { component = "COMPONENT_M19_VARMOD_V2", item = "pistol_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_M19_VARMOD_V3" },
            -- ["luxary_finish"] = { component = "COMPONENT_M19_VARMOD_V4" },
            -- ["luxary_finish"] = { component = "COMPONENT_M19_VARMOD_V5" },
            -- ["suppressor"] = { component = "COMPONENT_AT_PI_M19_SUPP" },
        }
    },
    [`weapon_spiderak`] = {
        name = "weapon_spiderak",
        label = "SPIDERAK",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SPIDERAK_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SPIDERAK_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_SPIDERAK_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SPIDERAK_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_pumpkin`] = {
        name = "weapon_pumpkin",
        label = "PUMPKIN",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_PUMPKIN_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_PUMPKIN_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_PUMPKIN_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_PUMPKIN_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_boneper`] = {
        name = "weapon_boneper",
        label = "BONEPER",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_BONEPER_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_BONEPER_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["scope"] = { component = "COMPONENT_AT_SCOPE_MAX", item = "sniper_scope", type = "scope" },
            -- ["scope_advanced"] = { component = "COMPONENT_AT_SCOPE_MAX" },
            ["suppressor"] = { component = "COMPONENT_BONEPER_AR_SUPP_02", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_desertpurple`] = {
        name = "weapon_desertpurple",
        label = "DESERTPURPLE",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_DESERT_CLIP_01", item = "pistol_defaultclip", type = "clip"},
            ["extendedclip"] = { component = "COMPONENT_DESERT_CLIP_02", item = "pistol_extendedclip", type = "clip"},
            ["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "pistol_flashlight", type = "flashlight"},
            ["suppressor"] = { component = "COMPONENT_AT_DESERT_SUPP", item = "pistol_suppressor", type = "suppressor" },
        }
    },
    [`weapon_desertnike`] = {
        name = "weapon_desertnike",
        label = "DESERT NIKE",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_DESERTNIKE_CLIP_01", item = "pistol_defaultclip", type = "clip"},
            ["extendedclip"] = { component = "COMPONENT_DESERTNIKE_CLIP_02", item = "pistol_extendedclip", type = "clip"},
            ["suppressor"] = { component = "COMPONENT_DESERTNIKE_PI_SUPP", item = "pistol_suppressor", type = "suppressor" },
        }
    },
    [`weapon_glocdkm`] = {
        name = "weapon_glocdkm",
        label = "GLOCDKM",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_GLOCKDM_CLIP_01", item = "pistol_defaultclip", type = "clip"},
            ["extendedclip"] = { component = "COMPONENT_GLOCKDM_CLIP_02", item = "pistol_extendedclip", type = "clip"},
            ["suppressor"] = { component = "COMPONENT_AT_GLOCKDM_SUPP", item = "pistol_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_GLOCKDMR_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_GLOCKDMG_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_GLOCKDMN_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_GLOCKDMB_SUPP" },
            ["luxary_finish"] = { component = "COMPONENT_GLOCKDM_VARMOD2", item = "pistol_luxuryfinish" },
            -- ["luxary_finish"] = { component = "COMPONENT_GLOCKDM_VARMOD3" },
            -- ["luxary_finish"] = { component = "COMPONENT_GLOCKDM_VARMOD4" },
            -- ["luxary_finish"] = { component = "COMPONENT_GLOCKDM_VARMOD5" }
        }
    },
    [`weapon_m4beast`] = {
        name = "weapon_m4beast",
        label = "M4BEAST",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M4BEAST_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_M4BEAST_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_M4BEAST_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_M4BEAST_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_m4goldbeast`] = {
        name = "weapon_m4goldbeast",
        label = "M4GOLDBEAST",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M4GOLDBEAST_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_M4GOLDBEAST_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_M4GOLDBEAST_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_M4GOLDBEAST_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_hellsniper`] = {
        name = "weapon_hellsniper",
        label = "HELLSNIPER",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_HELLSNIPER_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_HELLSNIPER_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_HELLSNIPER_SUPP", item = "sniper_suppressor", type = "suppressor" },
            ["scope"] = { component = "COMPONENT_HELLSNIPER_SCOPE_MAX", item = "sniper_scope", type = "scope" },
        }
    },
    [`weapon_357`] = {
        name = "weapon_357",
        label = ".357",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_357_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["luxary_finish"] = { component = "COMPONENT_REVOLVER_VARMOD4", item = "pistol_luxuryfinish" },
            -- ["luxary_finish"] = { component = "COMPONENT_REVOLVER_VARMOD6" },
            -- ["luxary_finish"] = { component = "COMPONENT_REVOLVER_VARMOD17" },
            -- ["luxary_finish"] = { component = "COMPONENT_REVOLVER_VARMOD22" },
            -- ["luxary_finish"] = { component = "COMPONENT_REVOLVER_VARMOD23" }
        }
    },
    [`weapon_revolverultra`] = {
        name = "weapon_revolverultra",
        label = "REVOLVERULTRA",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durability = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_REVOLVERULTRA_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_REVOLVERLEOSHOP_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
})