QBShared.AddWeapons({
    -- [`weapon_mcx`] = {
    --     name = "weapon_mcx",
    --     label = "MCX MODULAR",
    --     ammotype = "AMMO_RIFLE",
    --     type = "rifle",
    --     durablity = 0.15,
    --     recoil = 0.2,
    --     damagereason = "Ended / Shot down / Floored",
    --     attachments = {
    --         ["defaultclip"] = { component = "COMPONENT_MCX_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    --         ["extendedclip"] = { component = "COMPONENT_MCX_CLIP_02", item = "rifle_extendedclip", type = "clip" },
    --         -- ["extendedclip"] = { component = "COMPONENT_MCX_CLIP_04" },
    --         -- ["extendedclip"] = { component = "COMPONENT_MCX_CLIP_05" },
    --         ["drum"] = { component = "COMPONENT_MCX_CLIP_03", item = "rifle_drum", type = "clip" },
    --         ["flashlight"] = { component = "COMPONENT_MCX_FLSH_01", item = "rifle_flashlight", type = "flashlight" },
    --         ["scope"] = { component = "COMPONENT_MCX_SCOPE_01", item = "rifle_scope", type = "scope" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_02" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_03" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_04" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_05" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_06" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_07" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_08" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_09" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_10" },
    --         -- ["scope"] = { component = "COMPONENT_MCX_SCOPE_11" },
    --         ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
    --         -- ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_03" },
    --         -- ["suppressor"] = { component = "COMPONENT_AT_AR_SCAR17_SUPP_04" },
    --         ["stock"] = { component = "COMPONENT_MCX_STOCK1", item = "rifle_stock", type = "stock" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK1V2" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK1V3" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK2" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK3" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK4" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK5" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK6" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK7" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK8" },
    --         -- ["stock"] = { component = "COMPONENT_MCX_STOCK9" },
    --         ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP2", item = "rifle_grip", type = "grip" },
    --         -- ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP3" },
    --         -- ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP4" },
    --         -- ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP5" },
    --         -- ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP6" },
    --         -- ["grip"] = { component = "COMPONENT_AT_MCX_AFGRIP7" },
    --         ["luxary_finish"] = { component = "COMPONENT_MCX_FRAME_01", item = "rifle_luxary_finish", type = "luxary_finish" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_MCX_FRAME_02" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_MCX_FRAME_03" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_MCX_FRAME_04" },
    --         -- ["luxary_finish"] = { component = "COMPONENT_MCX_FRAME_05" }
    --     }
    -- },
    [`weapon_scom`] = {
        name = "weapon_scom",
        label = "SCOM",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SCOM_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            -- ["defaultclip"] = { component = "COMPONENT_SCOM4_CLIP_01" },
            -- ["defaultclip"] = { component = "COMPONENT_SCOM6_CLIP_01" },
            -- ["defaultclip"] = { component = "COMPONENT_SCOM7_CLIP_01" },
            -- ["defaultclip"] = { component = "COMPONENT_SCOM7_CLIP_01" },
            -- ["defaultclip"] = { component = "COMPONENT_SCOM_CLIP_02" },
            ["drum"] = { component = "COMPONENT_SCOM_CLIP_03", item = "pistol_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SCOM_SUPP", item = "pistol_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM2_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM3_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM4_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM5_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM6_SUPP" },
            -- ["suppressor"] = { component = "COMPONENT_AT_SCOM7_SUPP" },
            ["flashlight"] = { component = "COMPONENT_AT_SCOM_FLSH", item = "pistol_flashlight", type = "flashlight" },
            -- ["flashlight"] = { component = "COMPONENT_AT_SCOM4_FLSH" },
            -- ["flashlight"] = { component = "COMPONENT_AT_SCOM6_FLSH" },
            -- ["flashlight"] = { component = "COMPONENT_AT_SCOM7_FLSH" },
            ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD2", item = "pistol_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD3" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD4" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD5" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD6" },
            -- ["luxary_finish"] = { component = "COMPONENT_SCOM_VARMOD7" }
        }
    },
    [`weapon_boneak`] = {
        name = "weapon_boneak",
        label = "BONEAK",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKBONE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKBONE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKBONE_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKBONE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_akcupid`] = {
        name = "weapon_akcupid",
        label = "AKCUPID",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKCUPID_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKCUPID_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKCUPID_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKCUPID_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_aklover`] = {
        name = "weapon_aklover",
        label = "AKLOVER",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKLOVER_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKLOVER_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKLOVER_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKLOVER_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_akbombon`] = {
        name = "weapon_akbombon",
        label = "AKBOMBON",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKBOMBON_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKBOMBON_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKBOMBON_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKBOMBON_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_aklovenote`] = {
        name = "weapon_aklovenote",
        label = "AKLOVENOTE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKLOVENOTE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKLOVENOTE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKLOVENOTE_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKLOVENOTE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_akbadboy`] = {
        name = "weapon_akbadboy",
        label = "AKBADBOY",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AKBADBOY_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AKBADBOY_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_AKBADBOY_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_AKBADBOY_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_m4lover`] = {
        name = "weapon_m4lover",
        label = "M4LOVER",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M4LOVER_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_M4LOVER_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_M4LOVER_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_M4LOVER_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_rose`] = {
        name = "weapon_rose",
        label = "ROSE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ROSE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ROSE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_ROSE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_m4rose`] = {
        name = "weapon_m4rose",
        label = "M4ROSE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_M4ROSE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_M4ROSE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_M4ROSE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_pval`] = {
        name = "weapon_pval",
        label = "PVAL",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_PVAL_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_PVAL_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_PVAL_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_caveira`] = {
        name = "weapon_caveira",
        label = "CAVEIRA",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_CAVEIRA_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["flashlight"] = { component = "COMPONENT_AT_LOUISON_FLSH", item = "rifle_flashlight", type = "flashlight" },
            ["suppressor"] = { component = "COMPONENT_AT_CAVEIRA_SUPP", item = "rifle_suppressor", type = "suppressor" },
            ["luxary_finish"] = { component = "COMPONENT_CAVEIRA_VARMOD2", item = "rifle_luxary_finish", type = "luxary_finish" },
        }
    },
    [`weapon_ravenpistol`] = {
        name = "weapon_ravenpistol",
        label = "RAVENPISTOL",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_RAVENPISTOL_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_RAVENPISTOL_CLIP_02", item = "pistol_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_RAVEN_SUPP", item = "pistol_suppressor", type = "suppressor" },
        }
    },
    [`weapon_ravenshot`] = {
        name = "weapon_ravenshot",
        label = "RAVENSHOT",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["suppressor"] = { component = "COMPONENT_AT_RAVENSHOT_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_pblackval`] = {
        name = "weapon_pblackval",
        label = "PBLACKVAL",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_PBLACKVAL_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_PBLACKVAL_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_PBLACKVAL_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_valknife`] = {
        name = "weapon_valknife",
        label = "VALKNIFE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_valham`] = {
        name = "weapon_valham",
        label = "VALHAM",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_sniwolf`] = {
        name = "weapon_sniwolf",
        label = "SNIWOLF",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SNIWOLF_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SNIWOLF_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SNIWOLF_SUPP", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_wolfvern`] = {
        name = "weapon_wolfvern",
        label = "WOLFVERN",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_wolfknife`] = {
        name = "weapon_wolfknife",
        label = "WOLFKNIFE",
        ammotype = nil,
        type = "melee",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_ravenknife`] = {
        name = "weapon_ravenknife",
        label = "RAVENKNIFE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_snakeu`] = {
        name = "weapon_snakeu",
        label = "SNAKEU",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SNAKEU_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SNAKEU_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_SNAKEU_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SNAKEU_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_snakeper`] = {
        name = "weapon_snakeper",
        label = "SNAKEPER",
        ammotype = "AMMO_SNIPER",
        type = "sniper",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SNAKEPER_CLIP_01", item = "sniper_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SNAKEPER_CLIP_02", item = "sniper_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SNAKE_SUPP", item = "sniper_suppressor", type = "suppressor" },
        }
    },
    [`weapon_snakenade`] = {
        name = "weapon_snakenade",
        label = "WEAPON_SNAKENADE",
        ammotype = nil,
        type = "throwable",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_gutsling`] = {
        name = "weapon_gutsling",
        label = "GUTSLING",
        ammotype = "AMMO_HEAVY",
        type = "heavy",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_aa`] = {
        name = "weapon_aa",
        label = "AA12",
        ammotype = "AMMO_SHOTGUN",
        type = "shotgun",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_AA_CLIP_01", item = "shotgun_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_AA_CLIP_02", item = "shotgun_extendedclip", type = "clip" },
            -- ["defaultclip"] = { component = "COMPONENT_AA_CLIP_01ICE" },
            -- ["extendedclip"] = { component = "COMPONENT_AA_CLIP_02ICE" },
            -- ["defaultclip"] = { component = "COMPONENT_AA_CLIP_01GRAY" },
            -- ["extendedclip"] = { component = "COMPONENT_AA_CLIP_02GRAY" },
            ["luxary_finish"] = { component = "COMPONENT_AA_VARMOD", item = "shotgun_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_AA_VARMOD2" }
        }
    },
    [`weapon_680m`] = {
        name = "weapon_680m",
        label = "680M",
        ammotype = "AMMO_SHOTGUN",
        type = "shotgun",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["flashlight"] = { component = "COMPONENT_AT_680m_FLSH", item = "shotgun_flashlight", type = "flashlight" },
            ["stock"] = { component = "COMPONENT_680m_STOCK", item = "shotgun_stock", type = "stock" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK2" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK4" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK5" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK6" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK6V6" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK7" },
            -- ["stock"] = { component = "COMPONENT_680m_STOCK8" },
            ["suppressor"] = { component = "COMPONENT_AT_680m_SUPP", item = "shotgun_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_680m_SUPP2" },
            -- ["suppressor"] = { component = "COMPONENT_AT_680m_SUPP3" },
            ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_SAWN", item = "shotgun_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_LONG" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_SHORT" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_M5" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_M6" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_M7" },
            -- ["luxary_finish"] = { component = "COMPONENT_680_VARMOD_M8" }
        }
    },
[`weapon_assaultriflels`] = {
        name = "weapon_assaultriflels",
        label = "ASSAULTRIFLE MODULAR",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_ASSAULTRIFLELS_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_ASSAULTRIFLELS_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["extendedclip"] = { component = "COMPONENT_ASSAULTRIFLELS_CLIP_03" },
            ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE", item = "rifle_scope", type = "scope" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_01" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_02" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_03" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_04" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_05" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_06" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_08" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_09" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_11" },
            -- ["scope"] = { component = "COMPONENT_ASSAULTRIFLELS_SCOPE_12" },
            ["suppressor"] = { component = "COMPONENT_AT_LS_SUPP_01", item = "rifle_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_LS_SUPP_02" },
            -- ["suppressor"] = { component = "COMPONENT_AT_LS_SUPP_03" },
            ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK01", item = "rifle_stock", type = "stock" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK03" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK04" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK05" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK2" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK4" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK5" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK6" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK7" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK8" },
            -- ["stock"] = { component = "COMPONENT_ASSAULTRIFLELS_STOCK9" },
            ["luxary_finish"] = { component = "COMPONENT_ASSAULTRIFLELS_VARMOD_2", item = "rifle_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_ASSAULTRIFLELS_VARMOD_3" },
            -- ["luxary_finish"] = { component = "COMPONENT_ASSAULTRIFLELS_VARMOD_4" },
            -- ["luxary_finish"] = { component = "COMPONENT_ASSAULTRIFLELS_VARMOD_5" },
            -- ["luxary_finish"] = { component = "COMPONENT_ASSAULTRIFLELS_VARMOD_6" }
        }
    },
    [`weapon_diablo`] = {
        name = "weapon_diablo",
        label = "DIABLO",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_DIABLO_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_DIABLO_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_DIABLO_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_scarwhite`] = {
        name = "weapon_scarwhite",
        label = "SCARWHITE",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_SCARWHITE_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_SCARWHITE_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["drum"] = { component = "COMPONENT_SCARWHITE_CLIP_03", item = "rifle_drum", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_SCARWHITE_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_ravenknife`] = {
        name = "weapon_ravenknife",
        label = "RAVENKNIFE",
        ammotype = nil,
        type = "melee",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {}
    },
    [`weapon_ravenpistol`] = {
        name = "weapon_ravenpistol",
        label = "RAVENPISTOL",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_RAVENPISTOL_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_RAVENPISTOL_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            ["suppressor"] = { component = "COMPONENT_AT_RAVEN_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_ravenshot`] = {
        name = "weapon_ravenshot",
        label = "RAVENSHOT",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["suppressor"] = { component = "COMPONENT_AT_RAVENSHOT_SUPP", item = "rifle_suppressor", type = "suppressor" },
        }
    },
    [`weapon_caveira`] = {
        name = "weapon_caveira",
        label = "CAVEIRA",
        ammotype = "AMMO_PISTOL",
        type = "pistol",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_CAVEIRA_CLIP_01", item = "pistol_defaultclip", type = "clip" },
            ["luxary_finish"] = { component = "COMPONENT_CAVEIRA_VARMOD2", item = "pistol_luxary_finish", type = "luxary_finish" },
            ["flashlight"] = { component = "COMPONENT_AT_LOUISON_FLSH", item = "pistol_flashlight", type = "flashlight" },
            ["suppressor"] = { component = "COMPONENT_AT_CAVEIRA_SUPP", item = "pistol_suppressor", type = "suppressor" },
        }
    },
    [`weapon_ppsh41`] = {
        name = "weapon_ppsh41",
        label = "PPSH41",
        ammotype = "AMMO_RIFLE",
        type = "rifle",
        durablity = 0.15,
        recoil = 0.2,
        damagereason = "Ended / Shot down / Floored",
        attachments = {
            ["defaultclip"] = { component = "COMPONENT_PPSH41_CLIP_01", item = "rifle_defaultclip", type = "clip" },
            ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_02", item = "rifle_extendedclip", type = "clip" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_03" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_04" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_05" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_03_V2" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_01_V3" },
            -- ["extendedclip"] = { component = "COMPONENT_PPSH41_CLIP_02_V4" },
            ["suppressor"] = { component = "COMPONENT_AT_AR_PPSH41_SUPP_02", item = "rifle_suppressor", type = "suppressor" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_PPSH41_SUPP_03" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_PPSH41_SUPP_04_V2" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_PPSH41_SUPP_04_V3" },
            -- ["suppressor"] = { component = "COMPONENT_AT_AR_PPSH41_SUPP_04_V4" },
            ["stock"] = { component = "COMPONENT_PPSH41_STOCK", item = "rifle_stock", type = "stock" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK2" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK3" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK4" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK5" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK6" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK7" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK8" },
            -- ["stock"] = { component = "COMPONENT_PPSH41_STOCK9" },
            ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V2", item = "rifle_luxary_finish", type = "luxary_finish" },
            -- ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V3" },
            -- ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V4" },
            -- ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V2_V2" },
            -- ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V3_V3" },
            -- ["luxary_finish"] = { component = "COMPONENT_PPSH41_VARMOD_V2_V4" },
            ["scope"] = { component = "COMPONENT_AT_PPSH41_SCOPE_MEDIUMV3", item = "rifle_scope", type = "scope" },
            -- ["scope"] = { component = "COMPONENT_AT_PPSH41_SCOPE_MEDIUMV4" }
        }
    },
})