QBShared.AddWeapons({
    [`weapon_fnx45`] = {
        ["name"] = "weapon_fnx45",
        ["label"] = "FNX45",
        ["ammotype"] = "AMMO_PISTOL",
        ["damagereason"] = "Blasted",
        ["type"] = "pistol",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 1,
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MARKOMODS_FNX45_MAG_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MARKOMODS_FNX45_MAG_03", item = "pistol_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_MARKOMODS_FNX45_FLASH_01", item = "pistol_flashlight", },
            ["suppressor"] = { component = "COMPONENT_MARKOMODS_FNX45_SUPP_02", item = "pistol_suppressor", },
        },
    },
	[`weapon_g45`] = {
        ["name"] = "weapon_g45",
        ["label"] = "G45",
        ["ammotype"] = "AMMO_PISTOL",
        ["damagereason"] = "Blasted",
        ["type"] = "pistol",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 1,
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MARKOMODSG45_MAG_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MARKOMODSG45_MAG_04", item = "pistol_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_MARKOMODSG45_FLSH_01", item = "pistol_flashlight", },
            ["suppressor"] = { component = "COMPONENT_MARKOMODSG45_BARREL_02", item = "pistol_suppressor", },
            ["grip"] = { component = "COMPONENT_MARKOMODSG45_FRAME_03", item = "pistol_grip", },
        },
    },
	[`weapon_pm4`] = {
        ["name"] = "weapon_pm4",
        ["label"] = "PD M4",
        ["ammotype"] = "AMMO_RIFLE",
        ["damagereason"] = "Floored" ,
        ["type"] = "rifle",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 3,
        ["attachments"] = {
            ['defaultclip'] = { component = 'COMPONENT_MARKOMODS_SHARED_556MAG_01', item = 'rifle_defaultclip', type = 'clip', },
            ['flashlight'] = { component = 'COMPONENT_MARKOMODS_SHARED_LASER_02', item = 'rifle_flashlight', },
            ['scope'] = { component = 'COMPONENT_MARKOMODS_SHARED_SCOPE_02', item = 'rifle_scope', },
            ['suppressor'] = { component = 'COMPONENT_MARKOMODS_SHARED_SUPP_14', item = 'rifle_suppressor', },
            ['grip'] = { component = 'COMPONENT_MARKOMODS_SHARED_GRIP_07', item = 'rifle_grip', },
        },
    },
	[`weapon_mb47`] = {
        ["name"] = "weapon_mb47",
        ["label"] = "MB47",
        ["ammotype"] = "AMMO_RIFLE",
        ["damagereason"] = "Floored" ,
        ["type"] = "rifle",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 3,
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MARKOMODS_SHARED_556MAG_01", item = "rifle_defaultclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_MARKOMODS_SHARED_FLASH_07", item = "rifle_flashlight", },
            ["scope"] = { component = "COMPONENT_MARKOMODS_SHARED_SCOPE_03", item = "rifle_scope", },
            ["suppressor"] = { component = "COMPONENT_MARKOMODS_SHARED_MUZZLE_08", item = "rifle_suppressor", },
            ["grip"] = { component = "COMPONENT_MARKOMODS_SHARED_STOCK_08", item = "rifle_grip", },
        },
    },
    [`weapon_g17a`] = {
        ['name'] = 'weapon_g17a',
        ['label'] = 'G17A',
        ['ammotype'] = 'AMMO_PISTOL',
        ['damagereason'] = 'Blasted',
        ["type"] = "pistol",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 1,
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MARKOMODS_G17A_MAG_01", item = "pistol_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_MARKOMODS_G17A_MAG_02", item = "pistol_extendedclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_MARKOMODS_G17A_FLASH_01", item = "pistol_flashlight", },
        },
    },
	[`weapon_vector`] = {
        ['name'] = 'weapon_vector',
        ['label'] = 'Kriss Vector',
        ['ammotype'] = 'AMMO_SMG',
        ['damagereason'] = 'Riddled',
        ["type"] = "smg",
        ["recoil"] = 0.3,
        ["durability"] = 0.14,
        ["class"] = 2,
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_MARKOMODS_VECTOR_CLIP_1", item = "smg_defaultclip", type = "clip", },
            ["flashlight"] = { component = "COMPONENT_AT_AR_FLSH", item = "smg_flashlight", },
            ["scope"] = { component = "COMPONENT_MARKOMODS_SHARED_SCOPE_05", item = "smg_scope", },
            ["suppressor"] = { component = "COMPONENT_MARKOMODS_VECTOR_SUPP_4", item = "smg_suppressor", },
            ["grip"] = { component = "COMPONENT_MARKOMODS_SHARED_GRIP_08", item = "combatpdw_grip", },
        },
    },
})
