QBShared.AddWeapons({
    -- Thermal Katana Pack
    [`weapon_thermalkatana`] 	= {["name"] = "weapon_thermalkatana", 		["label"] = "Thermal Katana", 			["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana2`] 	= {["name"] = "weapon_thermalkatana2", 		["label"] = "Cyan Thermal Katana", 		["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana3`] 	= {["name"] = "weapon_thermalkatana3", 		["label"] = "Lime Thermal Katana", 		["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana4`] 	= {["name"] = "weapon_thermalkatana4", 		["label"] = "Pink Thermal Katana", 		["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana5`] 	= {["name"] = "weapon_thermalkatana5", 		["label"] = "Purple Thermal Katana", 	["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana6`] 	= {["name"] = "weapon_thermalkatana6", 		["label"] = "Red Thermal Katana", 		["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana7`] 	= {["name"] = "weapon_thermalkatana7", 		["label"] = "White Thermal Katana", 	["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_thermalkatana8`] 	= {["name"] = "weapon_thermalkatana8", 		["label"] = "Yellow Thermal Katana", 	["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_katana`] 			= {["name"] = "weapon_katana", 				["label"] = "Katana", 					["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},

    -- Katana Pack
	[`weapon_katana_02`]  = {["name"] = "weapon_katana_02", ["label"] = "Aikuchi",     ["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_katana_03`]  = {["name"] = "weapon_katana_03", ["label"] = "Asakusa",     ["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_katana_04`]  = {["name"] = "weapon_katana_04", ["label"] = "Kamakura",    ["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_katana_05`]  = {["name"] = "weapon_katana_05", ["label"] = "Kinai", 	   ["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},
	[`weapon_katana_06`]  = {["name"] = "weapon_katana_06", ["label"] = "Kano Matsuo", ["type"] = "melee", ["durability"] = 0.05,  ["class"] = "B", ["damagereason"] = "Stabbed"},

    [`weapon_shoe`] = {["name"] = "weapon_shoe",    ["label"] = "Shoe", ["type"] = "throwable", ["class"] = "C", ["throwable"] = true,   ["damagereason"] = "Whacked"},
    [`weapon_shiv`] = {["name"] = "weapon_shiv",    ["label"] = "Shiv", ["type"] = "melee",     ["class"] = "A", ["damagereason"] = "Stabbed"},
	[`weapon_staff`]            = {["name"] = "weapon_staff",  ["label"] = "Staff", ["class"] = "C", ["durability"] = 0.14, ["damagereason"] = "Whacked", },
	[`weapon_pan`]            = {["name"] = "weapon_pan",  ["label"] = "Pan", ["class"] = "C", ["durability"] = 0.14, ["damagereason"] = "Whacked", },
	[`weapon_scythe`]           = { ["name"] = "weapon_scythe",         ["label"] = "Death",                ["durability"] = 0.14, ["class"] = "B", ["damagereason"] = "DIE", },
	[`weapon_reindeer_horn`]  = { ["name"] = "weapon_reindeer_horn",   ["label"] = "Bat",   ["durability"] = 0.14, ["class"] = "C", ["damagereason"] = "Whacked", },
	[`weapon_candy_cane`]     = { ["name"] = "weapon_candy_cane",      ["label"] = "Bat",   ["durability"] = 0.14, ["class"] = "C", ["damagereason"] = "Whacked", },

    [`weapon_beanbagshotgun`]   = {["name"] = "weapon_beanbagshotgun",  ["label"] = "Beanbag Shotgun",      ["type"] = "shotgun",   ["durability"] = 0.14, ["recoil"] = 0.2,    ["ammotype"] = "AMMO_BEANBAG",  ["damagereason"] = "Blasted", },

	-- Vday
    [`glow_bat`]                = {["name"] = "glow_bat",  ["label"] = "XO Bat", ["class"] = "C", ["durability"] = 0.14, ["damagereason"] = "Whacked", },
	[`pink_axe`]                = {["name"] = "pink_axe",  ["label"] = "XO Axe", ["class"] = "B", ["durability"] = 0.14, ["damagereason"] = "Sliced", },
	[`val_clever`]              = {["name"] = "val_clever",  ["label"] = "XO Cleaver", ["class"] = "B", ["durability"] = 0.14, ["damagereason"] = "Chopped", },
	[`val_knife`]               = {["name"] = "val_knife",  ["label"] = "XO Knife", ["class"] = "B", ["durability"] = 0.14, ["damagereason"] = "Sliced", },
	[`val_purge_bat`]           = {["name"] = "val_purge_bat",  ["label"] = "XOXO Bat", ["class"] = "C", ["durability"] = 0.14, ["damagereason"] = "Whacked", },

	[`weapon_mk18b`] = {
		["name"] = "weapon_mk18b",
		["label"] = "MK18B Rifle",
		["type"] = "rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 3,
		["attachments"] = {},
	},
	[`weapon_g63`] = {
		["name"] = "weapon_g63",
		["label"] = "G36 Rifle",
		["type"] = "rifle",
		["ammotype"] = "AMMO_RIFLE",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 3,
		["attachments"] = {},
	},
	[`weapon_m700a`] = {
		["name"] = "weapon_m700a",
		["label"] = "M700 Sniper",
		["type"] = "rifle",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Sniped",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_mp9a`] = {
		["name"] = "weapon_mp9a",
		["label"] = "MP9",
		["type"] = "smg",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 2,
		["attachments"] = {},
	},
	[`weapon_minismg2`] = {
		["name"] = "weapon_minismg2",
		["label"] = "Skorpion",
		["type"] = "smg",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 2,
		["attachments"] = {},
	},
	[`weapon_minismg3`] = {
		["name"] = "weapon_minismg3",
		["label"] = "Mac-10",
		["type"] = "smg",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "Riddled",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 2,
		["attachments"] = {},
	},
	[`weapon_browning`] = {
		["name"] = "weapon_browning",
		["label"] = "Browning Hi-Power",
		["type"] = "pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_BROWNING_CLIP_01", item = "browning_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_BROWNING_CLIP_02", item = "browning_extendedclip", type = "clip" },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP_02", item = "pistol_suppressor" },
		},
	},
	[`weapon_glock`] = {
		["name"] = "weapon_glock",
		["label"] = "PD Glock 49",
		["type"] = "pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 1,
		["attachments"] = {},
	},
	[`weapon_dp9`] = {
		["name"] = "weapon_dp9",
		["label"] = "Diamondback DB9",
		["type"] = "pistol",
		["ammotype"] = "AMMO_PISTOL",
		["damagereason"] = "Blasted",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 1,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_DP9_CLIP_01", item = "dp9_defaultclip", type = "clip", },
			["extendedclip"] = { component = "COMPONENT_DP9_CLIP_02", item = "dp9_extendedclip", type = "clip", },
			["suppressor"] = { component = "COMPONENT_AT_PI_SUPP_02", item = "pistol_suppressor", },
		},
	},
	[`weapon_ltl`] = {
		["name"] = "weapon_ltl",
		["label"] = "BeanBag Shotgun",
		["type"] = "shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["attachments"] = {},
	},
	[`weapon_winchester`] = {
		["name"] = "weapon_winchester",
		["label"] = "Winchester Rifle",
		["type"] = "shotgun",
		["ammotype"] = "AMMO_SHOTGUN",
		["damagereason"] = "BOOMED!!",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 4,
		["attachments"] = {},
	},
	[`weapon_microsmg2`] = {
		["name"] = "weapon_microsmg2",
		["label"] = "Uzi",
		["type"] = "smg",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "BOOMED!!",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 2,
		["attachments"] = {
			["defaultclip"] = { component = "COMPONENT_UZI_CLIP_01", item = "microsmg2_defaultclip", type = "clip" },
			["extendedclip"] = { component = "COMPONENT_UZI_CLIP_02", item = "microsmg2_extendedclip", type = "clip" },
			["suppressor"] = { component = "COMPONENT_AT_UZI_SUPP", item = "smg_suppressor", type = "silencer" },
		},
	},
	[`weapon_microsmg3`] = {
		["name"] = "weapon_microsmg3",
		["label"] = "Mac-10",
		["type"] = "smg",
		["ammotype"] = "AMMO_SMG",
		["damagereason"] = "BOOMED!!",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 2,
		["attachments"] = {
			["extendedclip"] = { component = "COMPONENT_MICROSMG3_CLIP_02", item = "microsmg3_extendedclip", type = "clip" },
			["flashlight"] = { component = "COMPONENT_AT_PI_FLSH", item = "smg_flashlight" },
			["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "smg_scope" },
			["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "smg_suppressor", type = "silencer" },
			["luxuryfinish"] = { component = "COMPONENT_MICROSMG_VARMOD_LUXE", item = "microsmg3_luxuryfinish" },
		},
	},
		[`weapon_christmas_musket`] = {
		["name"] = "weapon_christmas_musket",
		["label"] = "Christmas Musket",
		["type"] = "sniper",
		["ammotype"] = "AMMO_SNIPER",
		["damagereason"] = "Floored",
		["recoil"] = 0.2,
		["durability"] = 0.14,
		["class"] = 3,
		["attachments"] = {},
	},
        [`WEAPON_DD11_B`] = {
        ["name"] = "WEAPON_DD11_B",
        ["label"] = "DDM4V7 Black (11.5)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG30_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP11_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_EXPS34_B", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_COMPONENT_BCM_B", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_COMPONENT_PEQ11_B", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_DD11_OD`] = {
        ["name"] = "WEAPON_DD11_OD",
        ["label"] = "DDM4V7 Army (11.5)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG30_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP11_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_EXPS34_B", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_B", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ11_B", item = "rifle_flashlight",},
        },
    },
    [`WEAPON_DD11_C`] = {
        ["name"] = "WEAPON_DD11_C",
        ["label"] = "DDM4V7 Tan (11.5)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG30_C", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP14_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_EXPS34_B", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_C", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ11_C", item = "rifle_flashlight",}, 
        },
   
    },
    [`WEAPON_DD14_B`] = {
        ["name"] = "WEAPON_DD14_B",
        ["label"] = "DDM4V7 Black (14)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGLINK_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP14_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_HHSVO_B", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_B", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_COMPONENT_PEQ14_B", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_DD14_OD`] = {
        ["name"] = "WEAPON_DD14_OD",
        ["label"] = "DDM4V7 Army (14)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGLINK_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP14_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_HHSVO_B", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_OD", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_COMPONENT_PEQ14_B", item = "rifle_flashlight",},   
        },
    },
    [`WEAPON_DD14_C`] = {
        ["name"] = "WEAPON_DD14_C",
        ["label"] = "DDM4V7 Tan (14)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGLINK_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP14_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_HHSVO_C", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_C", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ14_C", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_DD16_B`] = {
        ["name"] = "WEAPON_DD16_B",
        ["label"] = "DDM4V7 Black (16)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP16_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_VUDU_1X", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_B", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ16_B", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_DD16_OD`] = {
        ["name"] = "WEAPON_DD16_OD",
        ["label"] = "DDM4V7 Army (16)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP11_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_VUDU_1X", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_OD", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ14_B", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_DD16_C`] = {
        ["name"] = "WEAPON_DD16_C",
        ["label"] = "DDM4V7 Tan (16)",
        ["ammotype"] = "AMMO_RIFLE",
        ["type"] = "rifle",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
            ["defaultclip"] = { component = "COMPONENT_PMAG40_B", item = "rifle_defaultclip", type = "clip", },
            ["extendedclip"] = { component = "COMPONENT_PMAGRANGER_B", item = "rifle_extendedclip", type = "clip", },
            ["suppressor"] = { component = "COMPONENT_SOCOMSUP11_B", item = "rifle_suppressor", },
            ["scope"] = { component = "COMPONENT_VUDU_1X", item = "rifle_scope", },
            ["grip"] = { component = "COMPONENT_BCM_C", item = "rifle_grip", },
            ["flashlight"] = { componet = "COMPONENT_PEQ16_C", item = "rifle_flashlight",}, 
        },
    },
    [`WEAPON_BEANBAG`] = {
        ["name"] = "WEAPON_BEANBAG",
        ["label"] = "BEANBAG",
        ["ammotype"] = "AMMO_SHOTGUN",
        ["type"] = "shotgun",
        ["class"] = 3,
        ["durability"] = 0.14,
        ["recoil"] = 0.2,
        ["damagereason"] = "Floored",
        ["attachments"] = {
        },
    },
    [`WEAPON_MP9`] = {
    ["name"] = "WEAPON_MP9",
    ["label"] = "MP9 Police",
    ["ammotype"] = "AMMO_SMG",
    ["type"] = "smg",
    ["class"] = 2,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_MP9_CLIP_01", item = "rifle_defaultclip", type = "clip", },
        ["extendedclip"] = { component = "COMPONENT_MP9_CLIP_02", item = "rifle_extendedclip", type = "clip", },
        ["suppressor"] = { component = "COMPONENT_AT_AR_SUPP_02", item = "rifle_suppressor", },
        ["scope"] = { component = "COMPONENT_AT_SCOPE_MACRO", item = "rifle_scope", },
    },
},
[`WEAPON_DARKMATTER_M4`] = {
    ["name"] = "WEAPON_DARKMATTER_M4",
    ["label"] = "Darker Matter M4",
    ["ammotype"] = "AMMO_RIFLE",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DARKMATTER_M4_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DARKMATTER_MP40`] = {
    ["name"] = "WEAPON_DARKMATTER_MP40",
    ["label"] = "Darker Matter MP40",
    ["ammotype"] = "AMMO_SMG",
    ["type"] = "smg",
    ["class"] = 2,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DARKMATTER_MP40_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DARKMATTER_SP320`] = {
    ["name"] = "WEAPON_DARKMATTER_SP320",
    ["label"] = "Dark Matter SP320",
    ["ammotype"] = "AMMO_PISTOL",
    ["type"] = "pistol",
    ["class"] = 1,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DARKMATTER_SP320_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DARKMATTER_SR47`] = {
    ["name"] = "WEAPON_DARKMATTER_SR47",
    ["label"] = "Dark Matter SR47",
    ["ammotype"] = "AMMO_RIFLE",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DARKMATTER_SR47_CLIP_01", item = "rifle_defaultclip", type = "clip" },
        ["suppressor"] = { component = "COMPONENT_DARKMATTER_SR47_SUPP", item = "rifle_suppressor" },
    },
},
[`WEAPON_DARKMATTER_STRIKER`] = {
    ["name"] = "WEAPON_DARKMATTER_STRIKER",
    ["label"] = "Dark Matter Striker",
    ["ammotype"] = "AMMO_SMG",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DARKMATTER_STRIKER_CLIP_01", item = "rifle_defaultclip", type = "clip" },
        ["suppressor"] = { component = "COMPONENT_DARKMATTER_STRIKER_SUPP", item = "rifle_suppressor" },
    },
},
[`WEAPON_DIAMOND_M4`] = {
    ["name"] = "WEAPON_DIAMOND_M4",
    ["label"] = "Diamond M4",
    ["ammotype"] = "AMMO_RIFLE",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DIAMOND_M4_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DIAMOND_MP40`] = {
    ["name"] = "WEAPON_DIAMOND_MP40",
    ["label"] = "Diamond MP40",
    ["ammotype"] = "AMMO_SMG",
    ["type"] = "smg",
    ["class"] = 2,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DIAMOND_MP40_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DIAMOND_SP320`] = {
    ["name"] = "WEAPON_DIAMOND_SP320",
    ["label"] = "Diamond SP320",
    ["ammotype"] = "AMMO_PISTOL",
    ["type"] = "pistol",
    ["class"] = 1,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DIAMOND_SP320_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},
[`WEAPON_DIAMOND_SR47`] = {
    ["name"] = "WEAPON_DIAMOND_SR47",
    ["label"] = "Diamond SR47",
    ["ammotype"] = "AMMO_RIFLE",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_DIAMOND_SR47_CLIP_01", item = "rifle_defaultclip", type = "clip" },
        ["suppressor"] = { component = "COMPONENT_DIAMOND_SR47_SUPP", item = "rifle_suppressor" },
    },
},
[`WEAPON_MASTER_SR47`] = {
    ["name"] = "WEAPON_MASTER_SR47",
    ["label"] = "GRU2 Glowing",
    ["ammotype"] = "AMMO_RIFLE",
    ["type"] = "rifle",
    ["class"] = 3,
    ["durability"] = 0.14,
    ["recoil"] = 0.2,
    ["damagereason"] = "Floored",
    ["attachments"] = {
        ["defaultclip"] = { component = "COMPONENT_MASTER_SR47_CLIP_01", item = "rifle_defaultclip", type = "clip" },
    },
},


})
